### ISSUE TITLE
HTTP request for some curl versions returns 501

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1012]
Some versions of curl introduce headers that return 501 for some APIs. The problem seems to be the trasnfer.encoding header parameter. Tested with:

Curl version 7.61
Surf version 1.0.3
Url "https://api.coindesk.com/v1/bpi/currentprice.json"

Apparently in the surf repository has been created describing the error 
https://github.com/http-rs/surf/issues/72

**Comment by mariocao** [comment]
Closed as user agents have been already implemented.
