### ISSUE TITLE
Refactor wallet methods to use snake_case

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1027]
Currently, `wallet` api methods and its arguments are defined in camelCase and they should be snake_case.

**Comment by tmpolaczyk** [comment]
Btw, a breaking change in an API is the exact opposite of a refactor

**Comment by aesedepece** [comment]
+1

**Comment by tmpolaczyk** [comment]
Merged as 5e2ecb72956ca8fc74e0d93bc47fb7626ec2fd5d
