### ISSUE TITLE
Implement a method to create a prefilled wallet

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1029]
As a user running a Witnet node in testnet, I want be able to create a prefilled wallet with created addresses and wits on it.

**Comment by tmpolaczyk** [comment]
Would it be enough to add an optional argument to `createWallet`? Something like `{"prefill": [1000, 2000, 3000, 0]}` would generate 4 addresses with 1000, 2000, 3000, and 0 nanowits respectively.

Or would you prefer a more generic `faucet` method in the wallet to fund any address?

**Comment by Tommytrg** [comment]
IMO, it would be enough the optional argument
