### ISSUE TITLE
Add systemd service for witnet node

### ISSUE THREAD

**Issue by wimel** [witnet/witnet-rust#1043]
In [Compilation dependencies](https://github.com/witnet/witnet-rust/blob/master/docs/get-started/installation/from-source.md#compilation-dependencies)  it should be good to add the package `pkg-config` _(I have [this](https://pastebin.com/Yj60pD6z) error during install using this steps, solved with `sudo apt install pkg-config -y`)_ 

In the steps [Running witnet-rust from source code](https://github.com/witnet/witnet-rust/blob/master/docs/get-started/installation/from-source.md) is good option to add the steps to create systemd service for witnet node (all the steps with `root`).

- Create the file `witnet.service` in `/etc/systemd/system/`:
```
vim /etc/systemd/system/witnet.service
```

- Copy this _(change `<user>` for your user)_:
```
[Unit]
Description=Witnet full node

[Service]
ExecStart=/home/<user>/witnet-rust/target/release/witnet --config /home/<user>/conf.toml node server

User=<user>
Restart=always
RestartSec=3
LimitNOFILE=4096

[Install]
WantedBy=multi-user.target

```
→ The flag `--config` need a file in `home` of `<user>` with name `config.toml` to mod or add the configuration of node, [this](https://github.com/witnet/witnet-rust/blob/master/witnet.toml) is a good example to use.

→ If need to open the rpc port add the following in the `conf.toml`_(thanks to @tmpolaczyk on Discord)_:
```
[jsonrpc]
enabled = true
server_address = "127.0.0.1:21219"
```

- Enable service:
```
systemctl enable witnet.service
```

- Start service:
```
systemctl start witnet.service
```

- If for some reason the `witnet.service` file change, reload daemon:
```
systemctl daemon-reload
```

- Restart service:
```
systemctl restart witnet.service
```

- See the logs of service:
```
journalctl -f -u witnet.service
```

_Tested in Ubuntu 18.04.4 LTS_

**Comment by bertux** [comment]
Ok I will add the README to the pull request by correcting the howto above.

**Comment by bertux** [comment]
Solved by https://github.com/witnet/witnet-rust/pull/1128
