### ISSUE TITLE
Use `.witnet` as storage path by default

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1047]
## Description

In the past, we used to sandbox the storage of different testnet versions by using different paths for RocksDB.

Since chain data and identities are now sandboxed internally to the database (see #970, #976), we can stop changing paths. 

This would be a final change: storage paths would not need to be updated anymore, not even past the mainnet token generation event.

I'm suggesting using `.witnet` as the default path storage.

## Changes

This likely implies the following changes:
- Modifying `witnet.toml` so that the storage path reads `.witnet` instead of `.witnet-testnet-6`
- Modifying the defaults in the `witnet_config` sub-crate to reflect the same change.

## Impact

- The first testnet version that would make use of this change could be Testnet 7.
- Existing docker containers will likely change identities. Identities can be preserved by means of any of these:
  - editing the volume binding for the storage so that the old storage is bound into `.witnet` instead of `.witnet-testnet-6`
  - the key is exported and re-imported
- Existing non-docker nodes will likely change identities. Identities can be preserved by means of any of these:
  - renaming `.witnet-testnet-6` as `.witnet`
  - modifying `witnet.toml` so that storage path reads `.witnet` instead of `.witnet-testnet-6`
  - the key is exported and re-imported
- New docker containers or nodes are not affected by this change. Only caution is that the documentation needs to be updated so the recommended commands mention `.witnet` instead of `.witnet-testnet-6`.

**Comment by aesedepece** [comment]
As a side note, we could take the chance to rename the `testnet-3` configuration environment as simply `testnet`.

**Comment by tmpolaczyk** [comment]
> As a side note, we could take the chance to rename the `testnet-3` configuration environment as simply `testnet`.

In a separate commit please

**Comment by aesedepece** [comment]
@witnet/devs Are we in time for including this into the final `0.7.0` release?

The idea of updating the documentation every time we make a new release is quite unamusing to me.

**Comment by tmpolaczyk** [comment]
We can just edit the `witnet.toml` that's shipped with the release and change the defaults later.

Actually, the config crate sets the default to `.witnet-rust-testnet-3` :see_no_evil:

**Comment by aesedepece** [comment]
@tmpolaczyk you want to work on it or is it OK for me to take it?

**Comment by tmpolaczyk** [comment]
Go ahead

**Comment by aesedepece** [comment]
This is solved on master.
