### ISSUE TITLE
Add JSONRPC/CLI command for exporting current UTXO set

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1049]
## Description

There exists rough consensus in the Witnet community that balances from current testnets should be honored in further testnets. This is achieved through the genesis block feature, which enables starting a new chain whose initial state is not a blank slate but includes a snapshot of the UTXOs that existed before.

The genesis block feature is being tackled by #1032 / #1036 / #1046. However, we still need some convenient way to create a snapshot of the UTXO set at any time, so that a genesis block can be built from it.

### JSONRPC
- The node could use a `getUTXOs` JSONRPC method that returns snapshots of the UTXO set.
- When invoked with options `{ all: true }`, it would return the entire UTXO set.
- Otherwise, it would return only local UTXOs (those that belong to the master key of the node).
- (Optional) In the future, options `{ address: "twit1..." }` could return only the UTXOs belonging to such address.

### CLI
- Similarly, the same functionality could be exposed through the CLI.
- The output format for the CLI method should probably be the same (JSON) or maybe CSV. Or we could pivot over those through a flag (`--format JSON` / `--format CSV` / default: `--format `plain`)
- When invoked with the `--all` flag, it should print out the entire UTXO set.
- Otherwise, it would print out only local UTXOs as described before.
- (Optional) The same opportunity for an `--address` flag exists here.

## Consequences
- This is NOT a breaking change.
- The new JSONRPC and CLI methods should be reflected in the documentation.
- This may ease creation of light clients and other similar software.

**Comment by mariocao** [comment]
This issue can be considered closed as the node already provides the `utxos` CLI command:

```bash
./witnet node utxos --help

witnet-node-utxos 1.1.1
Get the unspent transaction outputs of the node

USAGE:
    witnet node utxos [FLAGS] [OPTIONS]

FLAGS:
    -h, --help       Prints help information
        --long       Show all the information about utxos
    -V, --version    Prints version information

OPTIONS:
    -n, --node <node>      Socket address of the Witnet node to query
        --address <pkh>    Public key hash for which to get UTXO information. If omitted, defaults to the node pkh

```
