### ISSUE TITLE
All `--pkh` arguments in the CLI should be renamed to `--address`

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1051]
## Description

So far, all methods optionally accepting addresses as argument expect those to be preceded by the `--pkh` flag.

`PKH` stands for "Public Key Hash". While it is true that addresses in Witnet are derived from the hash of the public key, there's no 1:1 correspondence between the concepts of "PKH" and "address". Namely, an address is the Bech32 serialized form of the first 20 bytes of a PKH.

Moreover, most smart contract developers and the broader Ethereum community is most likely not familiar at all with the concept of a PKH (even if Ethereum addresses are generated in the same way as Witnet addresses although serialized differently).

For all of this, I see no reason why we should keep miscalling addresses.

## Proposal

- Renaming all `--pkh` arguments as `--address`. 

## Consequences

- This is not a breaking change at the consensus / protocol level.
- This is an API breaking change if implemented at JSONRPC level.
- This is a minor usability challenge if only implemented at CLI level.
- This change should be reflected in the documentation.

**Comment by tmpolaczyk** [comment]
We could add `--address` as an alias to `--pkh`, so both syntaxes work. If we want to deprecate `--pkh`, then it is a breaking change.

**Comment by aesedepece** [comment]
I have updated the "consequences" section to better describe the severity of the changes. As you can see, they are different depending on whether we only change the CLI command or also the JSONRPC command.

I'm totally in for the alias. Then we can discuss if we want to keep the `--pkh` or not. For reasons of maintainability and preventing more severe breaking changes in the future, I'd stick to the smallest API possible, so I'd remove it.

**Comment by bertux** [comment]
implementing it at https://github.com/bertux/witnet-rust/tree/cli-pkh-rename

**Comment by bertux** [comment]
GetPkh name needs aliasing and updated about description
GetBalance GetReputation Send needs aliasing of their long parameter --pkh
