### ISSUE TITLE
Change getBlockChain API

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1058]
As discussed in #1046:

> I think we should change the API of the getBlockChain command, now when called with no arguments it returns the blocks from the last 50 epochs, when it should probably return the last 50 blocks.

* The `GetBlocksEpochRange` message already supports epoch range and block limit as two separate arguments
* Modify JSON-RPC `getBlockChain` method to accept `start_epoch` and `block_limit` as arguments.
* Modify CLI `getBlockChain` method and its documentation.
* Optional: add short human readable message to the output of `getBlockChain`:
"Showing all the blocks from the last 50 epochs (47 blocks)"
"Showing the first 100 blocks starting from epoch 0 (96 blocks)"

**Comment by aesedepece** [comment]
+1
