### ISSUE TITLE
Ensure that the bridge works well after testnet 0.7.x

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1059]

**Comment by tmpolaczyk** [comment]
The default configuration file `witnet_ethereum_bridge.toml` is missing the field `read_dr_hash_interval_ms`. Add it with default value `10_000`, and comment:

    # If readDrHash returns 0, try again later
    read_dr_hash_interval_ms = 10_000

**Comment by tmpolaczyk** [comment]
The bridge works but the price poller is stuck because some data requests are included in testnet6 but were never resolved.

**Comment by girazoki** [comment]
Epoch needs to be added to the data request claims and result reports
