### ISSUE TITLE
Modify wallet server address default

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1062]
Wallet server address in default config is 127.0.0.1:11212
This value should be the same than json_rpc server address to be able to connect wallet<>node

**Comment by tmpolaczyk** [comment]
`server_addr` is the one that the wallet exposes to sheikah, there is a `node_url` flag that defaults to `None`, so the wallet doesn't run if that variable is not set.

**Comment by aesedepece** [comment]
Is this still relevant?

**Comment by lrubiorod** [comment]
witnet.toml now includes the field node_url so it is solved
