### ISSUE TITLE
Create wallet method to validate mnemonics

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1068]
It would be really useful to have a `validate_mnemonics` method in the wallet to be able to call it in the create_wallet / import_wallet flow.
It should be easy to implement using because `tiny-bip39` contains [ErrorKind](https://docs.rs/tiny-bip39/0.7.1/bip39/enum.ErrorKind.html).

**Comment by aesedepece** [comment]
Why would this need to be a separate method to the one used when creating wallets? Do we need it outside of that flow?

**Comment by Tommytrg** [comment]
We don't have a method to validate mnemonics in the create wallet flow. When we create a wallet we ensure that the mnemonics the user enters are the same the of the previous step. But we don't have a way to validate mnemonics if the user don't generate mnemonics and try to use their own.

**Comment by kiminuo** [comment]
Actually, https://github.com/witnet/witnet-rust/blob/5feca51247e84ed9c4e55a6f2fa4df1005c98cf8/crypto/src/mnemonic.rs#L66 - `Mnemonic::from_phrase_lang_ref` behaves as that proposed `validate_mnemonics` method, doesn't it?

`tiny-bip39` test file https://github.com/maciejhirsz/tiny-bip39/blob/2e31ab034bb4a9d09270b7c0d5e41c2196175a47/tests/validate.rs#L28 uses that particular method.

**Comment by Tommytrg** [comment]
A few days ago, I implemented this method but i forgot to link the PR (#1079) to this issue. In fact, I used the code @kiminuo suggest. Thank you for your interest @kiminuo!
