### ISSUE TITLE
Make Config serializable and implement ShowConfig command

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1075]
https://github.com/witnet/witnet-rust/blob/master/src/cli/node/with_node.rs#L54

**Comment by tmpolaczyk** [comment]
I tried to implement this but got an error:

    Error: values must be emitted before tables

I think the solution is explained here:

https://github.com/alexcrichton/toml-rs/blob/7a43ac9e9c28afec8414f6d924024f5d33fe8fa2/src/ser.rs#L7

**Comment by twjang** [comment]
Hello! I implemented this feature and created a PR. Could you review https://github.com/witnet/witnet-rust/pull/1591 ?
