### ISSUE TITLE
Assessment of a relative limit of witnesses by data request

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1094]
Due to a big number of witnesses in a data request could overflow the network and allow gamification in the reputation system, one measure could be specifying a relative limit of witnesses by data request that is related for example to the ARS (Active Reputation System)

**Comment by aesedepece** [comment]
Of all the recently opened issues proposing assessments, this is specially compelling to me. Let me move it forward at least to the "Ready to be estimated" pipeline.

**Comment by mariocao** [comment]
Closed because there is already limit imposed by block/transaction weights
