### ISSUE TITLE
Assessment: progressive redistribution of the penalized and expired reputation

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1095]
Currently, all the penalised and expirated reputation is redistributed in the same epoch between the honest nodes. It produces big reputation movements, so the new reputation distribution does not represent the real honest contribution of the nodes to the system.

The idea is to find a progressive way to redistribute that extra reputation and see how affects to the system.

- Extra: One proposal is use that redistribution to provide more reputation to the nodes that have less reputation as a way to reduce the difference between nodes with high and low reputation when their behavior is honest

**Comment by mariocao** [comment]
Superseded by #1418
