### ISSUE TITLE
[Collaterals]: Adoption Plan

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1114]
As mandated by https://github.com/witnet/WIPs/pull/18

**Comment by tmpolaczyk** [comment]
Will be adopted in testnet 8

**Comment by aesedepece** [comment]
Hey, I don't think we have an adoption plan yet as for what WIP-0002 itself demands:

> As provided for by WIP-0001, for this proposal to be moved from the Draft to the Proposed stage, it needs to be updated so as to (1) introduce a reference implementation, (2) propose a value for the collateral_age and collateral_minimum consensus constant, and (3) propose a date for activation.

For this issue to be complete, `collateral_age` and `collateral_age` should be set, and a specific date of activation should be announced too. All of these need also to be written into the WIP-0002 document (which is not merged yet into the WIPs repository).

I'm reopening it if you don't mind :wink:

**Comment by tmpolaczyk** [comment]
Oh sorry, I thought that was already decided.

**Comment by aesedepece** [comment]
Superseded by #1175
