### ISSUE TITLE
Review copies in configuration documentation

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#112]
As requested in PR #85 , the copies in the configuration documentation should be reviewed (ideally by a native English-speaking person).

**Comment by aesedepece** [comment]
This needs an estimate.

**Comment by jrmoreau** [comment]
@aesedepece what do you mean by estimate?

**Comment by jrmoreau** [comment]
Copy has been reviewed. No changes to suggest. To confirm, this was for toml-file.md and no other docs files?
