### ISSUE TITLE
Unsolicited blocks are not worth being logged as errors

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1123]
If the node currently receives a block that was not queried for (by means of inventory requests), it logs an error message that reads:

https://github.com/witnet/witnet-rust/blob/c02dd48dd089a44dceb7ce8fd4f776a84636dcb8/node/src/actors/session/handlers.rs#L485

These are quite common while being in `WaitingConsensus` status or simply when doing the initial sync.

In my opinion these should not be logged as `Error` but rather `Debug`, as the sending of unsolicited fresh block candidates is the intended protocol behavior and therefore receiving them does not imply that there is something wrong with our node, connections or peers.
___
**This issue is marked as a [good-first-issue](https://github.com/witnet/witnet-rust/labels/good%20first%20issue%20%F0%9F%91%8B)**. If you need help solving this, feel free to ping its assigned menthor: @aesedepece

**Comment by aesedepece** [comment]
@Tommytrg this is perfect for a Gitcoin bounty.

**Comment by aesedepece** [comment]
I propose and assign myself as a mentor for this issue.

**Comment by tmpolaczyk** [comment]
It's logged as an error because it should never happen, it's a waste of bandwidth.

**Comment by aesedepece** [comment]
Yet it will keep happening because blocks are forwarded to all your peers, and you do not know which ones are not in the `Synced` with regards to excluding them :man_shrugging:

**Comment by tmpolaczyk** [comment]
If you mean candidate blocks, these are expected. If this error happens with block candidates then there is something wrong.

**Comment by aesedepece** [comment]
Yes, I mean block candidates. Those are exchanged using the same `BLOCK` message that is used as the response of inventory requests.

You never know the `ChainManager` state of your peers, so you are sometimes sending blocks to people that can't put those block on top of their chain because they are not in the `Synced` state.

In other words:
- There are two cases in which you receive `BLOCK` messages:
  1. When you are syncing yourself and send inventory requests to your peers.
  2. Simply every time a new block candidate appears, regardless of which synchronization state you are.

If we get a block candidate (case 2) while expecting the answer to an inventory request (case 1), an error is shown. 

My point is that neither that situation nor the one it is being messed with — a peer sending a case 1 block you didn't ask for — are totally harmless and there's no reason for raising an error, specially when (under my own interpretation of the universe) errors should only be shown if the user did something wrong or at least can take any action to solve them.

**Comment by tmpolaczyk** [comment]
> If we get a block candidate (case 2) while expecting the answer to an inventory request (case 1), an error is shown.

Then that's a bug in the code. While syncing we still need to keep track of the candidates, otherwise we can never sync to the last block. This error may cause nodes to fork, for example if they receive only half of the candidates, and the other half are lost due to this error.

After we fix that, we can discuss whether to move this log line to debug.

**Comment by aesedepece** [comment]
@lrubiorod what do you think? Do you know what we're doing with the candidates? I assume they're being ignored unless they belong to the epoch that immediately follows the one we have as the chain tip, so that synchronization can be finalized in that way.

**Comment by tmpolaczyk** [comment]
After PR #1262 this log was replaced with a do_send of `AddCandidates`.

https://github.com/witnet/witnet-rust/blob/3fb7b37bb95b939a4fe9c64da4a7e2b2ca3edf80/node/src/actors/session/handlers.rs#L519-L523

If we get some noisy logs related to block candidates in the future, look at the `AddCandidates` handler in `ChainManager`. Closing this issue.
