### ISSUE TITLE
Function `json_to_cbor` mistakenly manages all JSON numbers as Float

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1146]
As seen here, the RAD manager is currently managing all numeric values coming from JSON as `RadonFloat`:
https://github.com/witnet/witnet-rust/blob/2c0e9d614028867ab9c942bcd90c02124693cf2b/rad/src/operators/string.rs#L132

This leads to really poor UX for devs who are expecting those values to be operable using `RadonInteger` operators.

We should detect whether the numeric value has decimals, and cast to `RadonInteger` or `RadonFloat` automatically.

**Comment by tmpolaczyk** [comment]
So a data request using "StringParseJSON" will return floats when the input value is "1.12345" but will return integers when the float value is "1.00000"? That doesn't make any sense. If you want to use integers, use "StringParseInteger" or something.

**Comment by aesedepece** [comment]
> So a data request using "StringParseJSON" will return floats when the input value is "1.12345" but will return integers when the float value is "1.00000"? That doesn't make any sense. If you want to use integers, use "StringParseInteger" or something.

The issue here happens precisely when invoking `StringParseInteger`, which fails 100% of the time when it tries to process an integer that came wrapped in JSON, because ``StringParseJSON` is parsing all JSON numbers as `RadonFloat` instead of telling Integers apart.

And that's a problem — once you go from integer to float, there's no obvious way back because of precision, so we would be forcing users to `round()`, `floor()` or `ceil()` unnecessarily, as the integer nature of the number was explicitly stated in the original JSON.

It is true that the behavior you described is outrageous. But for "detect whether the numeric value has decimals" I rather meant telling if the JSON itself used a comma or not, so that:
- 1.2 → RadonFloat(1.2)
- 1.0 → RadonFloat(1.0)
- 1 → RadonInteger(1)

Does that make sense to you?

**Comment by tmpolaczyk** [comment]
That makes more sense. We should define the supported range of values somewhere and document (and test) this behavior. Right now we use 64-bit floats and 128-bit signed integers, right?

It would be nice to have some operator that forces the output to be integer regardless of the original value (using "FloatRound" on floats and "Identity" on integers), and similarly an operator to force the values to float (using "IntegerToFloat" or something).

**Comment by aesedepece** [comment]
> It would be nice to have some operator that forces the output to be integer regardless of the original value (using "FloatRound" on floats and "Identity" on integers), and similarly an operator to force the values to float (using "IntegerToFloat" or something).

That'd make sense, yes.

From a UX perspective, what I'm trying is not to force requests developers to use an operator just to make RADON behave exactly like one would expect from any RFC 8259 compliant software.
