### ISSUE TITLE
Make wallet provide more detailed information about different transaction types

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1153]
Yet to be discussed and specified (requires changes in Wallet API documentation)

**Comment by mariocao** [comment]
The specification is included in https://github.com/witnet/sheikah/issues/960

**Comment by Aimeelu668** [comment]
自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包（ https://www.uduncloud.com）。
通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by mariocao** [comment]
closed by #1166
