### ISSUE TITLE
last VRF output hash as input for the eligibility

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1155]
Currently we are using as input for the eligibility the last beacon, composed of the last block hash and checkpoint. The problem with this approach is that a miner can re-order transactions to affect positively its eligibility in the next epoch. We propose using the last VRF output hash, that today is utilized to check whether a miner is eligible, as input together with the checkpoint for eligibility equations. VRF hash outputs are deterministic given a private key and a message, and provide a pseudo-random output making unpredictable who the next miner will be.

**Comment by aesedepece** [comment]
AFAIK this is also solved by #1160. Closing it now.
