### ISSUE TITLE
Witnet Node De-anonymization

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1167]
@alvarodh5 commented on [Mon Apr 13 2020](https://github.com/witnet/witnet-ethereum-bridge/issues/76)

Finding discovered during Red4Sec security audit.

## Description
Witnet's whitepaper (https://witnet.io/witnet-whitepaper.pdf) describes that all requests made by the headless browser are made in such a way that a human cannot differentiate them from the rest of the normal traffic, preventing in this way any kind of attacks by administrators. However, this protection is not completely real since it has not been implemented yet.

![image](https://user-images.githubusercontent.com/9592881/79153521-44d89100-7dce-11ea-9b5c-92025dadac25.png)

&nbsp;

## Impact
It was possible to identify and de-anonymize Witnet's nodes. 
&nbsp;

## Steps to reproduce
Witnet blockchain is programmed in Rust, therefore, HTTP requests that come from libraries programmed in this same language, could come from Witnet network nodes. An example of a library could be the old Rust HTTP client (called cHTTP) renamed to the current isahc (https://github.com/sagebind/isahc).

Since all requests made by witnet nodes contain an unusual user-agent in their header, it is possible to identify them. This User-Agent is: 

- curl / X.X.X isahc / 0.7.6. 

![image](https://user-images.githubusercontent.com/9592881/79153537-4a35db80-7dce-11ea-8045-3914f6a5a86e.png)

During the tests, more than 20 witnet nodes have been identified:

![image](https://user-images.githubusercontent.com/9592881/79153567-59b52480-7dce-11ea-9ed5-c931c06b58cd.png)

![image](https://user-images.githubusercontent.com/9592881/79153581-5fab0580-7dce-11ea-9fd0-ae45c6cf999c.png)

Once we have identified the Witnet nodes, we can prepare our endpoint to return erroneous results, avoiding one of the main concerns specified in the whitepaper as shown below:

![image](https://user-images.githubusercontent.com/9592881/79153622-705b7b80-7dce-11ea-926c-ddf2d9fecee7.png)

In this way, if the request comes from the User-Agent that we have identified, as an example, it will show a false bitcoin price.  

![image](https://user-images.githubusercontent.com/9592881/79153654-7ea99780-7dce-11ea-9cb2-e3373e44a80a.png)

For the rest of users, the real price will be shown.
![image](https://user-images.githubusercontent.com/9592881/79153673-849f7880-7dce-11ea-9c1c-d923d370e6ff.png)
&nbsp;

## Mitigation
Apply a generic User-Agent in order to avoid or at least make the identification of nodes by webmasters and attackers more complicated.

**Comment by tmpolaczyk** [comment]
We can easily change the user agent to a generic one, and even make it configurable. But since an attacker could easily obtain a list of the IPs of all the witnet nodes, they could still attack specific nodes. So aside from changing the user agent, we should also use some proxy to perform the HTTP requests.
