### ISSUE TITLE
[Wallet] Refactor storage usage of bincode at rocksdb, data structures redundancy and scattered code

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1180]
Current wallet implementation does work but has some technical debt that will need to be addressed sooner or later. The most concerning areas are the use of bincode serialization in RocksDB, redundancy of some data structures and the fact that most of the business logic is scattered across many files, which makes it quite difficult to reason about most of the wallet features.

**Comment by Tommytrg** [comment]
We aren't going to implement this
