### ISSUE TITLE
[Documentation] Update RADON docs

### ISSUE THREAD

**Issue by clbartoli** [witnet/witnet-rust#1203]
The RADON can be found [here](https://github.com/witnet/witnet-rust/tree/master/docs/protocol/data-requests/radon). 
This documentation needs to be reviewed and updated where needed.

**Comment by mariocao** [comment]
Issue moved to [witnet/documentation #71](https://github.com/witnet/documentation/issues/71) via [**ZenHub**](https://www.zenhub.com/)
