### ISSUE TITLE
Wrong link to the witnet.toml 

### ISSUE THREAD

**Issue by wimel** [witnet/witnet-rust#1218]
In the [Doc](https://github.com/witnet/witnet-rust/releases) about releases on **"Operators not using Docker need to update `witnet.toml` files so they look like [this one](https://github.com/witnet/witnet-rust/releases/download/0.8.0/genesis_block.json) ..."** the link redirect to download the `genesis_block.json` but maybe the correct link is [this](https://github.com/witnet/witnet-rust/blob/master/witnet.toml) to the `witnet.toml` file.

And wil be possible to add the `sha` of the [genesis](https://github.com/witnet/genesis_block/blob/master/testnet_0.8.0_genesis_block.json) file in Documentation?  is useful to check that we have the right version of the genesis file.

**Comment by aesedepece** [comment]
Thanks for the heads-up @wimel, it is fixed now!
