### ISSUE TITLE
Superblock production and voting

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1232]
This issue should include:

- Adding a new consensus constant indicating the super block proposal period.
- Everytime epoch % block proposal period = 0 is reached, the **ARS members** should construct a superblock taking the last *period* DR and tally roots, computing a merkle tree to construct superblock DR and tally roots. With those roots, the superblock index and the previous superblock hash a superblock is constructed.
- The superblock is hashed, signed with the BLS key, and broadcasted

**Comment by lrubiorod** [comment]
Close the issue due to redundancy. Continue in #1182
