### ISSUE TITLE
Wallet should look for addresses when indexing blocks for the first time

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1260]
When using the sheikah feature "import wallet from mnemonics", the wallet does not index old transactions. This is because there are no addresses generated yet.

A simple fix would be to generate a fixed amount of addresses (100 internal and 100 external, for example) before starting the indexing process.

Another option would be to add a method to manually re-index the block chain.

**Comment by aesedepece** [comment]
Please note that the wallet already _does_ re-index the block chain when you import a wallet from mnemonics, as well as when creating a new one from scratch.

But reading the block chain alone is not enough for discovering past transactions. To fulfill that feature, what most wallets do is deriving the first address in each key chain (internal & external) and start looking for transactions that affect those addresses. Once you find the first address for the first time, then you derive the second one and keep indexing forward. This of course can be done in batches, as you mentioned.

This algorithm has some clear limitations, but those are well known and simply expected. Namely, addresses need to be derived in order (a transaction to/from address `n` will never be discovered if it exists prior to address `n - 1` in the chain).

**Comment by mariocao** [comment]
Closed in #1630
