### ISSUE TITLE
Discussion RadonErrors slashing and implement a solution

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1261]
**Problem:** Currently we detected that some "honest" nodes (witnet-rust releases provided through this repository) are being slashed by returning RadonError::RetrieveTimeOutError, that could be produced because some APIs can not provide a proper solution for all the requests done by the witnesses. That means, that witnesses that send this kind of error could be slashed (lose reputation and collateral).

**Proposed solutions:**
 - _No slash:_ In this case, nodes are incentivized with reputation and reward in case of Error's consensus, but they will not be slashed in case of being out of consensus. **Cons:** nodes could only commit errors due to they never will be slashed, and they could win reputation in some cases. One response to this could be that the incentives for having normal behavior are more proficient that to do this.
- _No slash, any reward:_ They will not be slashed but also not be rewarded when they commit an Error. **Cons:** Nodes are not incentivized to commit RadonErrors
- _No slash, no reputation reward:_ They will not be slashed but also not be rewarded with reputation in case of Error's consensus, but in that case they will rewarded with the wits are specified in the Data Requests. **Cons:** are the wits reward enough as an incentive for the node operators to commit an error?

**Other related cuestions:**
- Currently, utxos created in TallyTransactions that come from the collateral has to wait a collateral age period. That produce a high quantity of utxos in the net (dust). Removing that wait, we reduce the number of dust, and also the high consume for having a big utxo set in memory, but combined with one of the solution proposed before, we could increase the easiness to commit an attack with several identities.

- Some nodes are showing a high percentage of Error commitment, if there will be a random response from the source, all nodes will have more or less the same errors percentage. So it would be great detect what factor increase your error commitments number

**Comment by drcpu-github** [comment]
I actually pointed this 'problem' out in the Witnet Telegram a couple of days ago and proposed a slightly different solution, namely making the slashing progressive. This would entail that on an initial RadonError::RetrieveTimeOutError, you get slashed for x% of your reputation (instead of a flat 50%) and this would go up to y% in discrete steps of z% if you fail to reveal multiple times. The increase happens if you fail to reveal multiple times for a certain amount of DR's assigned to you (or epochs). The slash percentage can also decrease if you reveal on time for that amount amount of DR's assigned to you (or epochs).

I have a preference for DR's assigned to you, rather than epochs, because it seems more robust (you cannot take your node offline for a certain time resetting the slash percentage).

**Comment by aesedepece** [comment]
@drcpu-github thanks for commenting with your point of view!

Please note that reputation slashing is already cumulative inside a single epoch. That is, the `50%` reduction is applied as many times as you are considered a "liar".

It is also worth mentioning that slashed commits do not necessarily mean failure to reveal. Under current validation rules, your commits can be slashed for reasons that are external to your own node and rather related to the requester (specially crafted ill-intentioned requests) or the data sources (unreliable APIs that may fail or timeout now and then).

I think @lrubiorod's point in this particular issue is that regardless of the mechanism for calculating the amount of the slashing, it'll still "unfair" if the protocol slashes even a little bit of reputation from nodes that did actually nothing wrong.

This said, I do agree that current slashing amounts could be too aggressive and can even feel inappropriate in some cases, and something in the lines of what you proposed sounds good to me.

**Comment by drcpu-github** [comment]
Question: does a time-out of an API result in a different 'error' than failure to reveal?

In any case, I am only talking about failure to reveal penalties. The reason I proposed a progressive slashing system is that it is (I think) impossible to distinguish between a failure to reveal and not revealing on purpose.

Hypothetically speaking, if you could track where a DR is coming from (which smart contract), and you don't like the outcome of the value you are providing, you could decide to not reveal on purpose, trying to achieve a failed consensus (if not enough nodes reveal), thereby changing what should have happened. This should definitely be punished and you should not be able to do this often.

**Comment by aesedepece** [comment]
Failure to reveal is detected by the fact that we get a commitment from an identity but never receive the reveal follow-up. So, yes, those are very easy to tell apart.

**Comment by drcpu-github** [comment]
Doesn't a timeout from an API also result in a failure to reveal? Or do I have the order of operations wrong and is it: query API, commit, reveal, tally rather than commit, query API, reveal, tally?

**Comment by aesedepece** [comment]
@drcpu-github the retrieval process times out after only 2 seconds, and the timeout error gets committed. The rationale is that any data source that takes more than 2 seconds to return a value is not reliable enough for most use cases. The same can be said of a node whose Internet connection has such a high latency (if problem is on the side of the node, not on the data source).

**Comment by drcpu-github** [comment]
@aesedepece Yes, I know, and I think that is a great setting to prevent some attacks.

The point I'm trying to make is: how can you distiguish between an accidental time-out due to the API / node being too slow and a malicious one? A node could be trying to game the system because he does not like the answer that he would reveal. If you are opting for a complete no-slash approach, there is no deterrent to this.

One more lenient approach could be to only opt for a slashing if the time-out errors result in a failed DR because no consensus can be reached.

**Comment by lrubiorod** [comment]
> @aesedepece Yes, I know, and I think that is a great setting to prevent some attacks.
> 
> The point I'm trying to make is: how can you distiguish between an accidental time-out due to the API / node being too slow and a malicious one? A node could be trying to game the system because he does not like the answer that he would reveal. If you are opting for a complete no-slash approach, there is no deterrent to this.
> 
> One more lenient approach could be to only opt for a slashing if the time-out errors result in a failed DR because no consensus can be reached.

But if a data requester creates a request with a shitty source and everyone returns a RetrieveTimeOutError, I think they should not be slashed, and if they are in consensus they should get the wits reward

**Comment by drcpu-github** [comment]
Okay, that is true, I did not keep the reverse in mind. I'm not quite sure then how to discourage deliberately not revealing an value.
