### ISSUE TITLE
Blocks and data requests node stats do not add up upon resyncing

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1269]
A node that performs a resync will count their own blocks and data requests twice when deriving `nodeStats`, which will lead to the numbers in the stats not to add up correctly:

```
Block mining stats:
- Proposed blocks: 439
- Blocks included in the block chain: 57
Data Request mining stats:
- Times with eligibility to mine a data request: 3105
- Proposed commits: 3105
- Accepted commits: 7355
- Slashed commits: 107
```

The example above, as provided by @drcpu-github, is reading some absurd counts, like for example having more than twice accepted commits than the number of proposed commits.

**Comment by tmpolaczyk** [comment]
The problem is that the "proposed" stats cannot be obtained from the block chain, and therefore when resyncing they will be set to 0

**Comment by lrubiorod** [comment]
It was already fixed
