### ISSUE TITLE
Make `nodeStats` report `ChainManager`'s status and synchronization progress

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1278]
## Issue statement
Current users find it quite frustrating when they have to "guess" the state and synchronization progress of their own node by skimming through the logs or issuing commands like `getBalance`, which is intended for a different purpose and prompts the users with errors they are expected to make sense of.

## Proposed solution
We should make `nodeStats` report `ChainManager`'s status (`WaitingConsensus` / `Syncing` / `Synced` / `Live`) and synchronization progress.

**Comment by drcpu-github** [comment]
I was going to ask for a similar improvement. I'd say it's better if this is a separate CLI methode that output the current state as a json as that is a lot easier to parse into other applications.

For example, in one of my scripts, I have a small wrapper around the witnet binary to restart the node if "./witnet node getBalance" returns an error. It would be much cleaner if I can just call "./witnet node getStatus", parse the json it spits out and decide what to do next.

Cons: Yet another function to add to the abundance of already existing node functions.
Pros: Way easier to parse and also probably easier to finalize than nodeStats.

**Comment by aesedepece** [comment]
JSON responses for any method can always be queried for through the JSONRPC API that the node runs by default on port `21337`.  As a matter of fact, the CLI is calling the low-level JSONRPC method, parsing the JSON response and pretty printing it.

**Comment by aesedepece** [comment]
BTW this is how I keep my nodes running: :wink: 

```bash
#!/bin/bash

./witnet node server
sleep 5
$0
```

**Comment by drcpu-github** [comment]
Completely did not think of using a raw JSON RPC call, that works too.

Yeah, that would keep your node running, maybe I should use that instead of trying to do fancy stuff in Python. 😉

**Comment by tmpolaczyk** [comment]
There is a JSON-RPC method that returns the node status. Currently it contains synchronization status, number of peers, and reputation statistics. I believe this was added before we had the `peers` and `getReputation` methods.

https://github.com/witnet/witnet-rust/blob/3fb7b37bb95b939a4fe9c64da4a7e2b2ca3edf80/node/src/actors/json_rpc/json_rpc_methods.rs#L703-L713

This method is not implemented in the CLI because it is not clear what it should return.
