### ISSUE TITLE
Synchronization: allow to configure batch block size

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1279]
Currently there is a constant in the code that sets the maximum blocks number to be sent during synchronization process:

```
pub const MAX_BLOCKS_SYNC: usize = 500;
```

It cannot be changed in `witnet.toml`, and also changing it does only affect the blocks sent by this node, not the received blocks; meaning that there is no way for a node operator to set a smaller batch size. Nodes with slower storage or internet connection may want to lower the batch size, although the current limit of 500 does not seem to cause any major problems.

**Comment by aesedepece** [comment]
I have the hunch that batch size also has memory implications — the smaller the batch size, the smaller the memory footprint, as all blocks from a batch are kept in memory until the last one in the batch is validated. Is this correct?

**Comment by tmpolaczyk** [comment]
> I have the hunch that batch size also has memory implications — the smaller the batch size, the smaller the memory footprint, as all blocks from a batch are kept in memory until the last one in the batch is validated. Is this correct?

Correct.

Another problem is that when the node takes more than one epoch to consolidate all the blocks, strange things happen. For example, it drops all the peers thinking that they are out of consensus when that's not true.

**Comment by aesedepece** [comment]
At some point I even though that taking more than one epoch to consolidate a whole batch could even be one of the causes for #1262

**Comment by drcpu-github** [comment]
Is the memory footprint due to this parameter large? I remember discussing this regarding the previous testnet when the node crashed on the rpi. I hardcoded it to be smaller, but that did not seem to do a lot for the memory consumption.
