### ISSUE TITLE
Print a banner when the node goes into Live state

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1280]
It is certainly confusing for many users that they get quite flashy feedback when the node goes into Synced state, but then when it moves into Live it does so in a really quite manner.

We should implement a flashy banner for Live state too (and potentially remove the the Synced one?)

**Comment by tmpolaczyk** [comment]
I vote for renaming `SYNCED` to `ALMOST_SYNCED`, renaming `LIVE` to `SYNCED`, and showing the `SYNCED` banner in the new `SYNCED` state.

**Comment by aesedepece** [comment]
@tmpolaczyk see https://github.com/witnet/witnet-rust/pull/1281/files

**Comment by tmpolaczyk** [comment]
@aesedepece `LIVE` just doesn't have the same ring to it...
