### ISSUE TITLE
Prioritize transactions while building blocks

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1300]
This issue improves the building block feature in #1298 by taking into account the transaction fees in relation to the transaction weights. This should be done for the two different weighted transactions (value transfers and data requests).

One possible way to implement this feature is:

- pre-compute transaction `fee/weight` when received by the node (and added to mempool / data request pool)
- while mining, sort the mempool / data request pool by `fee/weight`

**Comment by aesedepece** [comment]
Solved by #1339
