### ISSUE TITLE
Investigate issues with SuperBlock 1 and SuperBlock 2

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1321]
Currently, every node will propose a superblock vote for superblock 1, and something strange happens for superblock 2: votes for superblock 1 and 2 are forwarded. For later superblocks, some superblock votes fail with "identity not in ARS".

**Comment by tmpolaczyk** [comment]
Also, it looks like nodes that are not synced yet, still send superblock votes.

**Comment by girazoki** [comment]
It might also be that the internal superblock state is not initialized when the node is synchronized for the first time, and therefore this causes a superblock forwarding by the recently synchronized node. We should either build the superblock structure as we synchronize or we prevent a recently synchronized node from sending a supervote until it builds the superblock state.

**Comment by girazoki** [comment]
The latter obviously has the downside that, if this recently synchronized node enters the ARS before constructing the first superblock, we loose its vote

**Comment by tmpolaczyk** [comment]
I think we should build the superblock structure as we synchronize, because this will allow us to use superblocks as a consensus mechanism in the future, instead of "synchronize to block 0abcd" we will be able to "synchronize to superblock 123ef".

**Comment by girazoki** [comment]
agree

**Comment by aesedepece** [comment]
Do we have a plan for this? Or are we just leaving superblocks out of the equation for this sprint?

**Comment by girazoki** [comment]
This should be fixed already with superblock construction while synchronizing

**Comment by girazoki** [comment]
Closed in 3068e8bcc83e8abeff052ce886866cdc14466f0b

**Comment by tmpolaczyk** [comment]
> every node will propose a superblock vote for superblock 1

This is still true, but it will be tracked #1367
