### ISSUE TITLE
Transactions in mempool can be assumed to be valid

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1352]
- Read the comments in #1308 carefully.
- This depends on and is blocked by #1308.
- Under the assumption that transactions are validated in real time as they are introduced into the in-memory transaction pool (mempool), and that #1308 is sorted out, we can safely assume that transactions that do exist in the mempool are valid and don't need any further validation when they are found in a block we are validating, or when we are collecting transactions for anchoring them into a block candidate that we are proposing.

**Comment by lrubiorod** [comment]
There are some proposal in #1385 and #1737 but they imply some problems for now (so they are currently closed)
