### ISSUE TITLE
Assess superblock-based reorganizations  

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1355]
[TBD]

**Comment by aesedepece** [comment]
Discussion is scheduled for next Thursday. @clbartoli has assessed the issue and prepared a briefing for everyone to be on the same page.

**Comment by girazoki** [comment]
Here the document https://hackmd.io/etWhHJPfTCqY1bZrMlUCpg?both

**Comment by aesedepece** [comment]
This has yet to be discussed, but it has been properly assessed by @clbartoli. Closing now.
