### ISSUE TITLE
make consolidated superblocks irreversible (only persist chainstate upon superblock consolidation, not on every block)

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1392]
This feature should prevent  the node from reversing after a superblock with sufficient majority has been consolidated. This implies that the chain state after the superblock consolidation should be persisted, as it will be the last confirmed state we know the network agreed upon

**Comment by aesedepece** [comment]
This is being addressed in #1404

**Comment by aesedepece** [comment]
This is now being addressed in #1420

**Comment by mariocao** [comment]
Closed in #1435
