### ISSUE TITLE
Detail data request result for each subscript operator 

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-rust#1401]
The rad request result when trying a data request should include the partial results of the operators within a subscript argument. 

As for example: 
```
partial_results: [
 0: { RadonString: '' },
 1: { RadonMap: {} },
 2: { RadonMap: {} },
 3: { RadonArray: [] },
 4: { script: [ 0: { RadonError: '' } ], result: { RadonError: '' }},
]
```

**Comment by aesedepece** [comment]
What is it giving to you right now? Only the final result of the subscript?

**Comment by aesedepece** [comment]
@gabaldon @Tommytrg so in #1402 I implemented a solution for this, but I covered `aggregate` and `tally`, so I will removing that know, stick to only `retrieve` and then ask you for feedback :wink:
