### ISSUE TITLE
When synchronizing, construct superblock when epoch has surpassed the superblock period

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1409]
When sycnrhonizing and receiving blocks from inventory, we utilize the checkpoint to check whether we need to construct superblocks (checkpoint % superblock_period =0). The truth is we should check whether the current_block_checkpoint % superblock_period is distinct from last_block_checkpoint % superblock_period

**Comment by mariocao** [comment]
Closed by #1410
