### ISSUE TITLE
Discuss about different approaches for redistributing reputation, especially in case of slashing

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1418]
Currently, when an identity is slashed or its reputation expires, that reputation is redistributed between all the identities that are committed a right value for a data request in that epoch. So there would be identities that earn more reputation than others doing the same job only due to be in the right moment. So... what is the best approach to redistribute reputation?

**Comment by drcpu-github** [comment]
And same here. ;)

**Comment by lrubiorod** [comment]
Conclusions: with the last update in #1456, to achieve a high quantity of reputations doesn't imply a high increase of your probabilities to mine a request. So the "unfair" reputation distribution that is currently working doesn't create an "unfair" behavior in the data request mining. Moreover, if all the reputation is not quickly reintroduced in the system, it produces that the security against sybil attack would be reduced. So, modify the current redistribution could produce more problems than solutions, and for that reasons we conclude that it should be not modified by the moment.
