### ISSUE TITLE
[wallet] Allow call "shutdown" method without a wallet open

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1475]
Currently, the `shutdown` method need a `session_id` argument event if there isn't any wallet open. Because of that, if user opens Sheikah and tries to close it without open a wallet, Sheikah won't close because it doesn't have a session_id to call `shutdown`.

Ideally, `shutdown` should be callable without arguments if no wallet is opened or the session_id has expired.

**Comment by mariocao** [comment]
Duplicated by #1474
