### ISSUE TITLE
Check state of FlatBuffers

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#151]
## Context
We've been recently having some issues with FlatBuffers related to the compiler and the rust lib using different versions and throwing some lifetime issues.

## Actionables
- [x] Check the state of FlatBuffers
- [x] Come with a combination of compiler and library versions that works
- [ ] Update development documentation to reflect the findings
- [ ] Present the findings to the rest of the team

## More info
Ask @mmartinbar and @Tommytrg

**Comment by Tommytrg** [comment]
**E0599** will be solved with a new flatbuffers PR
