### ISSUE TITLE
Fix transition from bootsratp signing committee to normal committee

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1525]
Currently the bootstrap committee is conformed by 3 identities, an the committee size is 100 identities. The expected flow would be to change from 3 to 100 in the moment of the transition, but with the progressive committee modification it will be increasing in 5 each. So it will be: 3...8...13...18 until achieve 100, that could be risky to use a very small random committee

**Comment by tmpolaczyk** [comment]
Closed by #1553, merged in #1557 as commit 6d51d00c02459e26ccd2d64a8e7c8674b827b63d
