### ISSUE TITLE
[Wallet] Error running wallet in mac due to openssl dependency

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1534]
In Sheikah, we are downloading and running a witnet wallet in the backgroud. Some mac users have reported that they can't run Sheikah due to they have the following problem:

![photo5962969321040884452](https://user-images.githubusercontent.com/24905681/92748159-28dd1980-f385-11ea-8396-5e77dc43fc34.jpg)

Some of them have been able to solve this problem linking `openssl` in this way https://stackoverflow.com/a/61280967/7405967.

Could you shed light on this problem? This is a big problem for Sheikah due to some mac users won't be able to run it.

**Comment by mariocao** [comment]
This issue was sort of fixed by using the following flags while building the release:

```bash
OPENSSL_STATIC=1 OPENSSL_DIR="" cargo build --release
```

**Comment by aesedepece** [comment]
To verify that the binary got OpenSSL statically linked, make sure that this command does not mention anything related to `openssl` nor `libcrypt`:
`otool -L target/release/witnet`
