### ISSUE TITLE
Discuss strategy for recommending sensible settings regarding retrieval proxies

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1542]

**Comment by Tommytrg** [comment]
@tmpolaczyk could you rebase this PR https://github.com/witnet/witnet-rust/pull/1523 to be able to see if something else is missing?

**Comment by aesedepece** [comment]
As per informal discussions, we have agreed that we will:
- give this feature its due visibility in the `Witnet.toml` file
- update the documentation with sensible recommendations on best practices
- do some community activation for node operators to adopt this opt-in feature

I think that should work for now.
