### ISSUE TITLE
Add "broadcast" method for sending actor messages to all consolidated outbound sessions

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#155]
For convenience when announcing new inventory items, it is convenient to have a handler in `SessionsManager` that will take an actor message and forward it to every consolidated outbound session.

This handler, `Broadcast<Message>`, should handle actor messages using the native `Message` type, NOT flatbuffers, NOR bytearrays NOR `WitnetMessage`s.

E.g.: sending a `Broadcast(AnnounceItem)` to `SessionManager` will produce the same effect than sending an `AnnounceItem` message to every consolidated outbound `Session`.

This `Broadcast<X>` handler should return the value returned by the `X` handler in `Session`. That is, it simply forwards the returned value back to the caller.

**Comment by tmpolaczyk** [comment]
Implemented in #161
