### ISSUE TITLE
Choose the right Mainnet consensus constants

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#1615]

**Comment by drcpu-github** [comment]
I'll open a bit of discussion here regarding the `collateral_age` consensus constant. Given that the choice was made to let transfered WIT's serve as collateral (understandably), I believe we need to up the collateral age value.

In the past two testnets, I have seen people split the rewards from the first block they minted over >50 addresses. If you mint in the first couple of epochs and split the reward, that results in a significant advantage to solve data requests, earn reputation and get a higher chance of minting early blocks leading to a skewed distribution of WITs.

An example: in testnet 0.9.3, I minted a block in the first 100 epochs and split the reward over 10(-ish) nodes. When the collateral matured, I sent a couple of data requests into the network and (almost) all of my 10 nodes entered the ARS. Of the first couple of thousand blocks, I minted about 0.5% of all blocks with (much) less than 0.1% of the total nodes in the network.

I do realize that there will now be extra competition as there are many more identities with unlocked funds from the genesis block. However, it is not straight-forward (for me) to estimate how many there will be, if they will have nodes running, and what the influence on early value splits will be. I don't think that upping the collateral age has a negative long-term influence and it does, partially, mitigate the effect of splitting early blocks over many identities.

I'd suggest setting the collateral age to, for example, one week. What do you think?
