### ISSUE TITLE
Implement or delete reducer and filter funcions in RAD engine

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1620]
There are some filter and reducer funcionts that are not implemented in the RAD engine:

![image](https://user-images.githubusercontent.com/24905681/95444746-6de17500-095e-11eb-8fbb-c9425f59e7ff.png)

![image](https://user-images.githubusercontent.com/24905681/95445023-cb75c180-095e-11eb-9ae6-2d49a96b0c16.png)

![image](https://user-images.githubusercontent.com/24905681/95445675-8d2cd200-095f-11eb-9fa0-62bb378a09e8.png)

![image](https://user-images.githubusercontent.com/24905681/95445859-cf561380-095f-11eb-8468-c20d36de9d18.png)

![image](https://user-images.githubusercontent.com/24905681/95446489-aaae6b80-0960-11eb-8021-f5105e496253.png)

Should this functions be implemented or be deleted from sheikah?

**Comment by tmpolaczyk** [comment]
These are all the filters and reducers, implemented or not:

```rust
pub enum RadonFilters {
    // Implemented
    DeviationStandard = 0x05,
    Mode = 0x08,

    // Not implemented
    GreaterThan = 0x00,
    LessThan = 0x01,
    Equals = 0x02,
    DeviationAbsolute = 0x03,
    DeviationRelative = 0x04,
    Top = 0x06,
    Bottom = 0x07,
    LessOrEqualThan = 0x80,
    GreaterOrEqualThan = 0x81,
    NotEquals = 0x82,
    NotDeviationAbsolute = 0x83,
    NotDeviationRelative = 0x84,
    NotDeviationStandard = 0x85,
    NotTop = 0x86,
    NotBottom = 0x87,
    NotMode = 0x88,
}

pub enum RadonReducers {
    // Implemented
    Mode = 0x02,
    AverageMean = 0x03,
    DeviationStandard = 0x07,

    // Not implemented
    Min = 0x00,
    Max = 0x01,
    AverageMeanWeighted = 0x04,
    AverageMedian = 0x05,
    AverageMedianWeighted = 0x06,
    DeviationAverageAbsolute = 0x08,
    DeviationMedianAbsolute = 0x09,
    DeviationMaximumAbsolute = 0x10,
}
```

**Comment by tmpolaczyk** [comment]
It looks like they won't be implemented, so we need to remove them from the other frontend libraries.
