### ISSUE TITLE
[Wallet] Return error creating a wallet with already used mnemonics

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#1631]
When importing a wallet in sheikah, it creates the wallet and then tries to unlock it. However, if the user is reusing mnemonics an already created wallet, it will not return an error and will fail if the user introduces a different password.

Because of that, it would be useful for Sheikah receive an error when the wallet is already created.

**Comment by mariocao** [comment]
The agreed approach is to return if the wallet exists during the `validate_mnemonics` phase. Later on, another issue will cover the creation of a wallet of an already
