### ISSUE TITLE
[Wallet] Load Balancer for the public node

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1632]
We should avoid having a single point of failure, and make sheikah and the wallet connect to potentially several public nodes

**Comment by tmpolaczyk** [comment]
Would it be enough to simply add a list of nodes from which to choose a random one at startup? Or do we need more features such as change the node if it stops responding, or it's not synced, or after x hours?

**Comment by girazoki** [comment]
I think it is reasonable as a start to have just a list of nodes.
