### ISSUE TITLE
[Wallet] Address movements are being re-indexed upon Tally arrivals

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1658]
`AddressInfo`s should not be re-indexed when Tallies are received by the wallet.

**Comment by tmpolaczyk** [comment]
Need more info, how to reproduce?

**Comment by aesedepece** [comment]
Is this somehow related to #1815 / #1817 ?

**Comment by tmpolaczyk** [comment]
I thought so, but it looks like the opposite issue. #1815 is about missing payments while this issue is about duplicated payments.

**Comment by lrubiorod** [comment]
We are trying to reproduce that issue, creating several requests, re synchronizing and producing reverts during active requests processes. Finally we couldn't reproduce the issue, so... close the issue by the moment

**Comment by mariocao** [comment]
It seems that the code that handles the address information updates ignores TallyTransactions.
They only contain refunds to data request creators and the protocol enforces that the tally output can only be set to the first used input of the DR.

```rust
fn _index_transaction(...) {
  // ...
  match txn.transaction {
      Transaction::ValueTransfer(_) | Transaction::Mint(_) => {
          // ...
      }
      _ => {}
  }
```
