### ISSUE TITLE
Calculating the hash of BN256 public keys is very expensive

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1668]
This is the code that calculates the hash of a BN256 public key, used in the function build_superblock to calculate the ARS hash:

```rust
impl Hashable for Bn256PublicKey {
    fn hash(&self) -> Hash {
        calculate_sha256(&self.to_uncompressed().unwrap()).into()
    }
}
```

`to_uncompressed` is an expensive operation, so we should avoid calling it here.

Possible solutions

* Cache the hash. The operation will still be expensive but only the first time a public key is used.
* Cache the uncompressed key. Same as above, but we can reuse the uncompressed key in other places.
* Store the uncompressed key. We can assess whether we need the compressed key or the uncompressed key, or even both, and calculate them ahead of time.
* Change the hash function to use compressed keys (BREAKING CHANGE). This depends on the bridge, and what is cheaper in ethereum.

**Comment by girazoki** [comment]
Any of the first three works, with a preference for the second one. The latest would be ideal but AFAIK it would complicate quite a bit the implementation of the bridge

**Comment by aesedepece** [comment]
Same take as @girazoki. If not using the uncompressed anywhere, I'd go with no. 1 for now.

**Comment by tmpolaczyk** [comment]
The uncompressed is not used anywhere, but I went with option 2. See #1669 for further discussion
