### ISSUE TITLE
[Wallet] If a user cancels the `create_vtt`, the used UTXOs stayed marked as already spent (but only for a period of time)

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#1718]
### Context:

The create and send value transfer were split into 2 different API calls (and steps):
 1. `create_vtt`: receives VTT parameters and returns the transaction object, so that the end-used may check all transaction fields.
 2. `send_transaction`: receives the transaction object and sends it to the node for its broadcasting.

### Problem:

Right now, the step 1 is marking UTXOs as used. If the Sheikah user, cancels the interrupts the send transaction process by clicking on "cancel", then step 2 is not executed but UTXO stay marked as used for a period of time.

Main consequence, is that after cancelling a send transaction, if the user has not enough additional UTXOS, it has to wait (~7 minutes) to be able to retry sending again a transaction.

### Potential solution:

A possible solution is that step 1 does not mutate any state in the wallet, and only step 2 really does the logic of marking UTXOs as used. However, as pointed out by some colleagues, this issues might be a good opportunity to discuss if the send transaction flow makes sense and if it could be simplified.

Making these changes on step 2 would require to add some logic in the `send_transaction` method from the `App` actor and most probably in the function of `add_local_movement` of `repository/wallet/mod.rs`.

**Comment by tmpolaczyk** [comment]
Fixed in #1725
