### ISSUE TITLE
Nodes stuck because "Superblock consensus different from current superblock"

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1738]
When there is a superblock consensus different from the one created by the node, the expected behavior is to roll back to the previous valid superblock N - 1 and synchronize to the latest one (N). However, it is possible that the node is only connected to peers that have also reverted, and in that case the node will not be able to synchronize to the latest superblock (N).

In that case the node will think that it is synced, it will ignore the consensus for superblock N, and it will process the votes for the next superblock (N + 2). Since it is expected that this superblock N + 2 will not reach a majority, the node will revert back to the superblock N - 1 and the process will start again. The only way to exit this loop is to have a majority of outbound peers on the correct superblock.

**Comment by girazoki** [comment]
Done in #1739
