### ISSUE TITLE
panic if bridge node is stopped between included and resolved state

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1768]
[2020-12-04T10:14:47Z INFO  witnet_ethereum_bridge::actors::wrb_requests_periodic_sync] [1] Request has been included
thread 'tokio-runtime-worker-11' panicked at 'no entry found for key', bridges/ethereum/src/eth.rs:172:21

**Comment by girazoki** [comment]
This happened while hahving one node including and reporting and the other one relaying blocks

**Comment by tmpolaczyk** [comment]
Not happening in master
