### ISSUE TITLE
[Bridge] Do not show errors for data request number 0

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-rust#1776]
Currently the bridge node shows an error when retrieving the data request 0. We should discuss how to deal with these kind of errors and decide how to show them

**Comment by girazoki** [comment]
Potentially we should review all bridge logs and decide what to change

**Comment by tmpolaczyk** [comment]
Alternatively, we could design a simple web-based interface to see the rough status of the bridge node: list of data requests and the state of each of them, as that should be enough for most of our debugging. Adding some kind of JSON-RPC API to get the internal state of the bridge should be very easy, but I would need help to design a client.

**Comment by aesedepece** [comment]
> Currently the bridge node shows an error when retrieving the data request 0. We should discuss how to deal with these kind of errors and decide how to show them

Simply put a comparison somewhere and skip it if `index == 0`.

**Comment by Tommytrg** [comment]
@lrubiorod @tmpolaczyk is this still an issue with the current bridge?
