### ISSUE TITLE
"Superblock consensus unknown" when constructing superblock in AlmostSynced state

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1809]
When a node synchronizes to the network it cannot process the received `SUPERBLOCK_VOTE` messages, so they are stored in a temporary buffer `temp_superblock_votes`. When the node moves into `Synced` state, all those votes are processed so that they are counted for the next superblock consensus.

The problem is that sometimes the node finishes the synchronization just before the superblock consensus. It moves into `AlmostSynced` state, and tries achieve superblock consensus but fails because it has 0 votes, because the votes are only added in `Synced` state. This results in a warning "Superblock consensus unknown", and delays the synchronization for at least 2 epochs.

So we could try to process the `temp_superblock_votes` when moving to `AlmostSynced` state, or we could add a check to the superblock consensus logic: if `temp_superblock_votes` is not empty, add all those votes before calculating consensus.

**Comment by aesedepece** [comment]
Can confirm this happens some times.

**Comment by lrubiorod** [comment]
I prefer the first one, we could process the superblock votes when we are in the AlmostSynced state, because in that moment we are 0 or 1 block behind the chain, and the votes comes from the other superepoch, so theorically, we should be able to process properly the votes
