### ISSUE TITLE
[Wallet] Wallet only shows genesis transactions after resync

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1818]
Steps to reproduce:

* Unlock a synced wallet with some transactions from the genesis block and some transactions from a later block
* Press resync button
* After it shows the genesis transactions, close the wallet
* Unlock the wallet again and wait
* The wallet will sync but only the genesis transactions will be shown.

**Comment by tmpolaczyk** [comment]
Most probably the "resync" flag is not stored when the wallet closes, so the wallet doesn't expect the transactions to be already in the database, here:

https://github.com/witnet/witnet-rust/blob/fd5ef15fc9027361425c13edba86ce4cdd5d2f43/wallet/src/repository/wallet/mod.rs#L759-L761

I guess that we can skip that check and index the transaction even if it already exists

**Comment by aesedepece** [comment]
In case we don't come to agreement on a reasonable solution for this, we can buy ourselves some time with a "low hanging fruit" mitigation: extending lifetime of sessions to 24h so that it can perform the entire resynchronization at once.
