### ISSUE TITLE
JSONRPC/CLI method for transaction details should show confirmation / finality status

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1828]
There's no simple way for a node operator to check for confirmation / finality status of a transaction.

In the same way as the `transaction` JSONRPC/CLI method shows the block in which a transaction was last found, it should also show whether that block has been confirmed by a superblock or not.

**Comment by drcpu-github** [comment]
That would be quite convenient. Right now, to display mined vs confirmed in the explorer, I fetch the block for the transaction in question and look up the confirmed flag there. This would definitely lighten the load on the backend. 👍
