### ISSUE TITLE
[Wallet] Show confirmed balance when the wallet is resynced

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-rust#1836]
The balance shown when resyncing the wallet does not show the confirmed balance until a superblock is confirmed or the user logs in the wallet again.
When resyncing, It should show the balance confirmed in previous superblocks.

**Comment by aesedepece** [comment]
Good one. All blocks received while either syncing or resyncing are already confirmed by a superblock, so any balance derived from them is inherently confirmed.
