### ISSUE TITLE
rpc call error  by curl 

### ISSUE THREAD

**Issue by fourseaLee** [witnet/witnet-rust#1882]
curl -X POST --data '{"jsonrpc":"2.0","method":"blockchain","params":{},"id":"1"}'  -H 'Content-Type: application/json' http://127.0.0.1:21338
I have runned rpc 'blockchain' to scan blockchain info. but it seem to be error like this:
![图片](https://user-images.githubusercontent.com/25864430/111097090-d1aa4280-857b-11eb-93a7-b38c75828ffb.png)

**Comment by tmpolaczyk** [comment]
Hi, this error is because you are trying to use JSON-RPC over HTTP when the witnet node expects JSON-RPC over TCP. This can be solved by using `nc` instead of `curl`:

    echo '{"jsonrpc":"2.0","method":"blockchain","params":{},"id":"1"}' | nc 127.0.0.1 21338

Or you can use the blockchain command, using the same syntax as when starting the node:

    witnet node blockchain
