### ISSUE TITLE
Send different error codes for different error messages

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet-rust#1889]
To allow a full internationalization in Sheikah we need to differentiate the error messages by code.
It would be nice to have a list of error codes with their corresponding error message.

**Comment by tmpolaczyk** [comment]
This is the function that converts a wallet error into a JSON-RPC error with (code, message, data) fields:

https://github.com/witnet/witnet-rust/blob/cc772097b883d7470298328ac625200bfc163a74/wallet/src/actors/app/error.rs#L32

I think most of the errors are "Validation Error" with code 400, and the `data` field contains the actual errors. The data field is `[[field, error_msg]]`, so I guess that the easiest solution would be to change it to ``[[field, code, error_msg, data]]``, or something similar.
