### ISSUE TITLE
Add minimum difficulty to data request eligibility

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1911]
PR #1884 implements a minimum mining difficulty so that in extreme cases when the ars size is small, the probability of mining a block is not 100%.

However, data request eligibility does not have a minimum difficulty, so in that case the probability of being eligible for resolving a data request can be 100%. This results in extreme flooding on the network because every node with enough collateral will send a commit transaciton, and potential forks because commit transactions are expensive to validate and some nodes may not be able to keep up under that load.

**Comment by tmpolaczyk** [comment]
Unresolved question: should we allow 100% eligibility?

Currently, the identities with most reputation may have a 100% chance of being eligible for some data requests. The formula is something like `target = reputation / total_reputation * threshold_factor`. `target` will be a number between 0.0 and 1.0 that represents the probability of creating a valid VRF proof. The threshold_factor depends on the number of witnesses of the data request, and it ensures that the average number of eligible identities is high enough. So adding a minimum difficulty here (for example 10%) will reduce the average number of commits per data request unless we also adjust the threshold_factor calculation, but that will require an analysis of the algorithm to ensure we don't break anything. But we may want to prevent some identities from having 100% eligibility to increase the decentralization of the network, for example. I think it's not worth it to make complex changes to this algorithm, but we have plenty of time until a "third hard fork" to fix this issue, so any suggestions welcome.

Proposal: only apply minimum difficulty to identities that are not in the ARS

This would solve the spamming problem we have seen when the ARS size is suddenly reduced, while all the other cases will work the same way as before. The only danger would be setting the minimum too low, because that may result in data requests having too few commits, and that will mean that the ARS will not get updated. I guess the value should make sure that on a data request with 125 witnesses there will be at least 250 commits out of 2000 inactive identities, so 12.5%?

Note that with a minimum of 100% the mainnet has eventually recovered, so not setting a minimum is also a possibility.

**Comment by drcpu-github** [comment]
I want to voice two concerns:

1. 100% eligibility should probably not be possible as, in my opinion, that paves the way for manipulating data requests. Imagine if you have multiple high-reputation nodes and a set of them can always commit to answering a certain type of data request. That seems to make it way too easy to manipulate them.

2. Applying a minimum difficulty only to identities not in the ARS seems like it could lead to centralization of reputation? If identities in the ARS have it easier to commit to solving a data request than the ones outside of the ARS, I can see that happening. I know reputation expires over time and that there are a lot more identities outside the ARS than inside, but I would be very careful with implementing something like this.

**Comment by lrubiorod** [comment]
Currently we are using eligibility instead of reputation to choose which identities are able to solve data requests, so in normal cases, I think anyone could obtain a 100% of eligibility. With the current numbers, if we check the eligibility of the most reputed node is 0.07% so if we multiply by 100, that is the most often witnesses number, it would obtain a 7% of eligibility.

In my opinion, the problem is when we have a big rollback and the ARS achieve a really low number. In that moment, the difficulty would be really low and the commits start to spamming the network, as we see during the upgrading to the second hard fork. I would prefer to create a minimum in the `total_reputation` of the formula that @tmpolaczyk provides

**Comment by tmpolaczyk** [comment]
@lrubiorod adding a minimum to `total_reputation` makes sense, because then the number of commits will depend on the number of witnesses. We should not forget about the "extra commit rounds" which increase the probability, so when setting this minimum we should ensure that a data request with 125 witnesses, after 4 commit rounds, does not reach 100% eligibility for nodes with 1 point of reputation.

@drcpu-github regarding 2) it's true that applying the limit only on inactive identities introduces an asymmetry between active inactive identities, so that may be dangerous. I suggested that because I thought that if we limit the probability of all the identities too much it may cause some data requests to be unsolved because of "not enough commits". But we can simply use a more relaxed limit to avoid that problem, and it's easier to implement the same limit for all the identities.

And regarding 1) it is a complex topic because if we decrease the maximum eligibility from 100% to 10%, for example, then an attacker can use 10 nodes instead of 1 to achieve the same result as before. So we can make the attack 10x more expensive, but it will still be possible. I think a better solution would be to make it more difficult to accumulate reputation, as there are already some measures in place such as reputation expiration.

**Comment by aesedepece** [comment]
This was bundled in the 1.2.2 release. Further discussion on keeping or removing these changes shall be conducted on a new issue.

**Comment by tmpolaczyk** [comment]
Let's not forget to add tests, because the current implementation may be wrong as it returns 100% eligibility sometimes.
