### ISSUE TITLE
Check viability of `BlockHeader.version` field repurpose for TAPI support signals

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#1920]

**Comment by tmpolaczyk** [comment]
`BlockHeader.version` can be used for TAPI support signals.

The version field affects the block hash so it is not possible to change it after the block is created (it is tamper proof), and nodes running on old software accept any value in the version field.

Furthermore, the version field can be renamed without breaking the storage or the protobuf messages, but it must be a `u32`.

The only strange detail is that the genesis block has version 1 while all the other mined blocks have version 0.

**Comment by aesedepece** [comment]
> The only strange detail is that the genesis block has version 1 while all the other mined blocks have version 0.

That's a funny fact. Shouldn't be a problem at all :)
