### ISSUE TITLE
Investigate why some panics stop the node and other ones don't

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1934]
For example, this panic:

https://github.com/witnet/witnet-rust/blob/1ac9e4974cbb22ce9930f1449d5f3269675e9e7a/node/src/actors/chain_manager/actor.rs#L121-L123

Is meant to stop the node, as the user is expected to delete the corrupted storage or restore a backup.

However the observed behavior is that the chain manager dies but the rest of the node actors keep running. This results in a node that is not usable.

This is a problem because the docker script that runs the node detects when the node panics and automatically restarts it, but now that won't work as nodes that panic will keep running.

So, investigate why does that happen and how to prevent it.

A simple solution would be to handle this in the actor "stopped" method. If it's possible to detect that the actor is stopping because of a panic, then we can stop the entire system.

**Comment by aesedepece** [comment]
In a parallel universe, we got this:

```rust
storage_mngr::get::<_, ChainState>(&storage_keys::chain_state_key(magic))
    .into_actor(act)
    .then(|chain_state_from_storage, _, _| {
        let result = match chain_state_from_storage {
            Ok(chain_state) => (chain_state, config),
            Err(e) => {
                log::error!("Error while getting chain state from storage: {}", e);

                (None, config)
            }
        };

        actix::fut::ok(result)
    })
```

Which I'm not saying it's what we want, because as you can imagine, this silently causes a reinitialization of the chain state and a full resync of the chain.
