### ISSUE TITLE
Improve node behavior in SuperBlockConsensus::Different case

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1963]
The current behavior when the superblock consensus is different than the node consensus is the following:

* Drop peers with the same highest_block_checkpoint than us
* Restore chain state from storage
* Move to WaitingConsensus

https://github.com/witnet/witnet-rust/blob/641da5bb9f8ede85023bf50c5e07ff51267b35ed/node/src/actors/chain_manager/mod.rs#L1490

Note that we have no guarantees that the new peers will be on the desired chain, so not sure how will the node recover in that case.

I think it's impossible to make the node sync to the target superblock with the current protocol, so I propose a simple change: make sure that the new peers are on the target superblock. The handshake process already includes the superblock beacon, so we could make the SessionsManager only accept peers with the correct superblock beacon. If no valid peers are found after N epochs we can fall back to the old process, but that will have the same problems as before.

So this would be the new behavior:

* Drop peers that are not on the target_superblock_hash
* Only allow to connect to peers that are on target_superblock_hash
* Restore chain state from storage
* Move to WaitingConsensus

**Comment by aesedepece** [comment]
Can this be closed?

**Comment by tmpolaczyk** [comment]
PR #1975 implemented "Only allow to connect to peers that are on target_superblock_hash".

We are missing the first step, "Drop peers that are not on the target_superblock_hash". The current behavior is to not drop any peers until the next epoch. That is related to issue #1977: we cannot immediately drop any peers because they don't give us enough information.

But I think that we can reuse issue #1977 to track that last missing step (or dismiss it if not needed).
