### ISSUE TITLE
Set LastBeacon right after consolidating superblock

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1977]
The `SessionsManager` stores the `LastBeacon`, which is the last consolidated block and superblock, and it's used in the handshake process to drop peers that are on a different or outdated chain.

Currently, the `LastBeacon` is set once every epoch, right after consolidating a new block. However, superblock consolidation happens later at the middle of the epoch, and the `LastBeacon` will not change until the next epoch. This introduces a delay of half an epoch during which the node doesn't know if its outbound peers have consolidated the correct superblock, or are forked and should be dropped. This would be nice to have for PR #1975, but the alternative is to simply wait half an epoch which isn't too bad.

So we should assess whether it is safe to set the `LastBeacon` right after consolidating a new superblock, because maybe it can cause problems if half of the network introduces this change and the other half does not.

Update: actually, superblock consolidation is triggered by the PeersBeacons handler, so it will happen as soon as all the outbound peers have sent their beacons, or after half an epoch if some peers do not send beacons. So the worst case is not half an epoch, but one epoch.

**Comment by tmpolaczyk** [comment]
So, after merging #1975, nodes will set the superblock beacon as soon as possible. This should allow us to implement the missing step of issue #1963: "Drop peers that are not on the target_superblock_hash".

The implementation should do the following when the consensus superblock is different from the local superblock:

* For each outbound peer, ask them for their LastBeacon.
* Peers that send the consensus superblock will be kept.
* Peers that send the old superblock were "forked" in the same chain as us, those will be dropped.
 
TODO: how do we know if the peers send the old superblock because they reverted, and not because they have not consolidated the new one just yet?

**Comment by lrubiorod** [comment]
> TODO: how do we know if the peers send the old superblock because they reverted, and not because they have not consolidated the new one just yet?

We do not know, but in #1975 we drop peers that doesn't send the new superblock but we only ice them when the epoch would be different to the epoch where superblock consolidation happens (epoch%10 != 0)
