### ISSUE TITLE
Optimization of the `broadcast` functionality

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#198]
**Description**

Some optimizations could be performed regarding `Broadcast` functionality, as suggested by @tmpolaczyk in this [discussion](https://github.com/witnet/witnet-rust/pull/194#discussion_r236700291).

Until now, the `Broadcast` functionality in the `SessionsManager` is used to force the sending of an `Actix` message to all outbound `Session` actors. Upon the reception of those `Actix` messages, the `Session` actors may do whatever they want (store something in the database, send something through the network, print a message log...).

When...
1) The task that those `Session` actors perform when receiving the `Actix` message is just the creation of a network message and its sending through the network connection
2) That message does not depend on any of the `Session` parameters, i.e., the message is the same for all `Session`
... then the creation of the network message and its serialization into a `Vec<u8>` could be performed outside the `Session`, just once, and not for every `Session`.

Then, that `Vec<u8>` would be simply used as payload in the `Actix` message broadcasted to all `Session` and, upon reception of that message, each `Session` actor would just transmit it through the network connection.

**Comment by aesedepece** [comment]
Creation of Witnet protocol messages should only take place inside the `Session` actor. Even if the suggested optimization makes a lot of sense, we should preserve current separation of concerns. This could open the door for `Session` to add support for multiple network protocols and transports in the future with no impact on the rest of the application.
