### ISSUE TITLE
Bridge: retry on timeout

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#1982]
Currently if there is any error with the ethereum client, the bridge ignores that call and will probably retry later. However, if the ethereum client has disconnected, all future calls will also fail with an error. The only solution in that case is to restart the bridge.

Ideally the ethereum client should be a separate actor with the ability to detect that the client has disconnected, and reconnect automatically.

**Comment by mariocao** [comment]
It seems that the function `check_ethereum_node_running` is not working.

@clbartoli and I started the bridge without an Ethereum node, and the output was:

```console
[2021-06-28T10:39:05Z DEBUG witnet_centralized_ethereum_bridge] Ethereum node is running at http://127.0.0.1:9544
```

**Comment by mariocao** [comment]
The logs of the conducted tests regarding the connection with the witnet node part:

- [x] 1. Node is down, and bridge cannot start: if panics with an error message
- [x] 2. Node and Bridge are up and running, and suddenly the node is disconnected: it stops working and it cannot recover even if Witnet node is re-connected.

We also checked:
- [x] Data request IDs between contract and database are working well
       - WRB Contracts have an empty DR at index 0
       - WRB Contracts `dataRequestCount` function will always return the length + 1 (because of DR 0). For example, count = 73, the last DR that can be queried is 72.
