### ISSUE TITLE
Check session type in GetPeers handler in Session

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#200]
**Description**

As discussed [here](https://github.com/witnet/witnet-rust/pull/194#discussion_r236741562), not checking the session type in the `Session` before sending a `GetPeers` protocol message through the network connection might be a mistake.

**Fix**

Check the session type in the `GetPeers` handler for the `Session` actor. If the session type is not outbound, do not create and send the `GetPeers` protocol message through the network connection.

**Comment by tmpolaczyk** [comment]
Fixed in 6d0d762
