### ISSUE TITLE
[Bridge] Re-send data request if `pending` for more than `timeout`

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#2018]
The actor `wit_poller` can get stuck polling the witnet network for a data request report if a revert occurs (while waiting a DR to be resolved).

The idea is that if a DR in `pending` state is stuck for more than a period, the `dr_sender` should be notified to re-send the data request again.

**Comment by tmpolaczyk** [comment]
This is already implemented, as can be seen in the config file:

```toml
# If the data request has been sent to witnet but it is not included in a block, retry after this many milliseconds
dr_tx_unresolved_timeout_ms = 600_000 # 10 minutes
```
