### ISSUE TITLE
Set activation information for WIP-00017 (median)

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#2054]
In existing reference implementation add the following:

- [x] WIP number should be WIP-0017
- [x] Activation bit and  date as described in WIP

**Comment by aesedepece** [comment]
Discussion is here:
https://github.com/witnet/witnet-rust/discussions/2055

**Comment by mariocao** [comment]
Closed by https://github.com/witnet/WIPs/pull/71
