### ISSUE TITLE
Assess deterministic ordering of reveals inside tallies for RNG functionality

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2057]

**Comment by lrubiorod** [comment]
Conclusions:
- Bytes from reveals will be reduced to 32 bytes in case of more than it, and completed with 0s in case of less
- Reveals sorting will be changed from pkh to hash(pkh+dr_pointer)

**Comment by aesedepece** [comment]
Regarding padding, let's make sure that user input falls into the LSB and the pad is added on the MSB.

(Ofc it would work the same in the opposite way, this comment is only with the purpose of standardization)
