### ISSUE TITLE
Unimplemented reducer `DeviationMaximumAbsolute` should have code `0x0A`

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2060]
Unimplemented reducer `DeviationMaximumAbsolute` is currently listed as `0x10`
https://github.com/witnet/witnet-rust/blob/d5bbf322e74026825d6fbd56c6f39d801c609113/rad/src/reducers/mod.rs#L34

This was originally intended to be `0d10` in decimal, which in hex makes `0x0A`.

**Comment by tmpolaczyk** [comment]
This is safe to change as long as the operator remains unimplemented. So we can fix it in the master branch, without TAPI.

**Comment by tmpolaczyk** [comment]
Fixed in commit 9fd5df66393440055087b2bd23fcacec4d1fef4d
