### ISSUE TITLE
RADType::Rng is decoded as RADType::HttpGet (protobuf defaults unknown enum values to 0)

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#2066]
While testing pull request #2053, we have noticed that old nodes seem to silently convert `Rng` retrieval sources into `HttpGet` retrieval sources. The cause seems to be the protobuf behavior to set unknown fields to 0 [(source)](https://developers.google.com/protocol-buffers/docs/proto3#enum), which is a problem in this case because the definition of `RADType` is:

https://github.com/witnet/witnet-rust/blob/0287689be241681b7342f3a604f1c103c79f6903/schemas/witnet/witnet.proto#L119-L121

In PR #2053, that definition is updated to:

```protobuf
 enum RADType { 
     HttpGet = 0;
     Rng = 1;
 } 
```

But this makes old nodes decode `1` as `0`, since they do not know about the `Rng` variant.

Fortunately this is the only `enum` defined in the schema, so this issue should only affect the `RADType` enum.

The fix would be to eventually have an enum like this:

```protobuf
 enum RADType {
     Unknown = 0;
     HttpGet = 1;
     Rng = 2;
 }
```

But it is not known if such a change can be safely implemented, as this protobuf schema is also used in some external libraries such as the witnet-ethereum-bridge.

**Comment by lrubiorod** [comment]
Close in #2053
