### ISSUE TITLE
Add a maximum value to "data_request_timeout_milliseconds" configurable parameter

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#2081]
Currently we are detecting that some requests that should be solved with a RequestTimeoutError are not being committed. It could be due to some miners increase this field more than half epoch, and after this time a commit will be considered invalid. To avoid this situation, a maximum value could be added.

Half epoch is 22,5 seconds, but we should leave time to broadcast it. In my opinion, 10 seconds is enough time to report a source as a RetrievalTimeoutError

**Comment by aesedepece** [comment]
At the end of the day, if I was using this feature, I would set it to somewhere between 2 to 5 seconds, so a hard limit anywhere between 10 to 20 seconds makes total sense to me (under the assumption that 2.5 seconds is enough for a commitment message to flood ~99% of the network)

**Comment by tmpolaczyk** [comment]
For the record, the default in config.rs and in the witnet.toml is set to 2 seconds.
