### ISSUE TITLE
Revisit libp2p integration assesment

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-rust#2126]

**Comment by Tommytrg** [comment]
After revisiting the assessment that @tmpolaczyk did regarding libp2p, we have four different options:

1. Re-implement witnet on top of libp2p
2. Add libp2p messages on top of witnet
3. Use libp2p as the transport, but keep legacy witnet code
4. Implement an ad-hoc solution inspired by libp2p

The conclusion is that implementing any of these options will require depending on libp2p, which is a critical one-way decision. Before investing more development effort into it, we need to precisely analyze each option's pros and cons.
