### ISSUE TITLE
Cannot find the binary path

### ISSUE THREAD

**Issue by Kaleb47** [witnet/witnet-rust#2165]
So I cd in a file directory called `data_structures`, run cargo build and I get this error.

```
 Compiling witnet_data_structures v0.3.2 (/Users/kalebamarante/witnet-rust/data_structures)
error: failed to run custom build command for `witnet_data_structures v0.3.2 (/Users/kalebamarante/witnet-rust/data_structures)`

Caused by:
  process didn't exit successfully: `/Users/kalebamarante/witnet-rust/target/debug/build/witnet_data_structures-767d9cb39346f6d8/build-script-build` (exit status: 101)
  --- stdout
  cargo:protos=/Users/kalebamarante/witnet-rust/data_structures/../schemas/witnet

  --- stderr
  thread 'main' panicked at 'protoc binary not found: cannot find binary path', /Users/kalebamarante/.cargo/registry/src/github.com-1ecc6299db9ec823/protoc-2.27.1/src/lib.rs:209:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I opened the lib.rs and took me to this code.

```
impl Protoc {
    /// New `protoc` command from `$PATH`
    pub fn from_env_path() -> Protoc {
        match which::which("protoc") {
            Ok(path) => Protoc {
                exec: path.into_os_string(),
            },
            Err(e) => {
                panic!("protoc binary not found: {}", e);
            }
        }
    }
```

I know syntactically the code makes sense. To make sure this was not an ARM64 conflict, I ran the code in gitpod and got the same error. My colleague ran the same code and got the same error.

**Comment by drcpu-github** [comment]
Did you install all dependencies as per [the docs](https://docs.witnet.io/developer-reference/compile-from-source-code)? It looks like you don't have the protobuf compiler installed.

**Comment by aesedepece** [comment]
Hi @Kaleb47 you are most likely missing the Protobuf compiler as a dynamic dependency.

That is, you need to install it in your system. It is called `protobuf-compiler` or `protoc` on most GNU/Linux distros and `protobuf` on MacOS. 

Please let me know if that solves the issue for you!

**Comment by Kaleb47** [comment]
> Hi @Kaleb47 you are most likely missing the Protobuf compiler as a dynamic dependency.
> 
> That is, you need to install it in your system. It is called `protobuf-compiler` or `protoc` on most GNU/Linux distros and `protobuf` on MacOS.
> 
> Please let me know if that solves the issue for you!

how do i install that?

**Comment by aesedepece** [comment]
@Kaleb47 you need to download the genesis block file from here:
https://raw.githubusercontent.com/witnet/genesis_block/master/latest/genesis_block.json

And then put it in the specified location (`.witnet/config/genesis_block.json`). You can also change that location by editing the `witnet.toml` configuration file
