### ISSUE TITLE
Add support for HTTP-POST and StringParseXml in wallet

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#2186]
Now that the WIPs have been activated, we need to add support for these features.

**Comment by tmpolaczyk** [comment]
Also in witnet-requests-js.

**Comment by aesedepece** [comment]
@tmpolaczyk what are the changes needed for the wallet?

As per the toolkit and witnet-requests-js, this does the trick: https://github.com/witnet/witnet-requests-js/pull/66

**Comment by aesedepece** [comment]
@Tommytrg @gabaldon  can you confirm that no changes were needed to make this features work in Sheikah?

**Comment by Tommytrg** [comment]
I can confirm that the features were implemented in Sheikah with the current state of the wallet
