### ISSUE TITLE
Incorrect collateral minimum comparison in dr_sender.rs

### ISSUE THREAD

**Issue by drcpu-github** [witnet/witnet-rust#2224]
https://github.com/witnet/witnet-rust/blob/82d395274faf66794681dff6ec05f28e81cefb59/bridges/centralized-ethereum/src/actors/dr_sender.rs#L268

Should this not be 1_000_000_000 since all values are always specified as nanoWit?

**Comment by aesedepece** [comment]
I think you are right @drcpu-github :+1:

**Comment by aesedepece** [comment]
In the DoD of this issue, let's include empirical verification that this validation actually works in practice.
