### ISSUE TITLE
Wallet can't confidently create a 2nd outgoing transaction while a 1st transaction is still pending

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2250]
# The problem
- The wallet component was initially created as a backend to the Sheikah wallet app.
- It was an assumption that Sheikah users wouldn't create 2 transactions in a row in the lapse of 1 block. And even if they did, they would be ok retrying the second one after a minute if it failed.
- The Witnet protocol doesn't allow creating and spending an UTXO inside the same block.
- The node component implements logic that caches out recently used UTXOs to prevent any attempt of double spending when 2 transactions are created in a row.
- As far as I can tell, the wallet doesn't include such protection.
- This may be causing accidental double spend attempts for "programmatic users" (e.g. exchanges). In case that a withdrawal .transaction is issued while a previous one is still pending, there's a possibility for both transactions to use one or more UTXOs in common. When broadcasting, there will be an error saying that the UTXO is no longer available for spend.

# The solution
- Implement caching logic in the wallet that prevents a UTXO from being "mounted" as input into a transaction if it was recently used in another one.
- This shall use a timeout to "unmark" used UTXOs if the transaction that used it was not confirmed in a while.
- The node already implements all that logic, so we can replicate, or even better, unify.

# Immediate mitigations for users before a proper fix is implemented
1. Split the balance in your wallet across multiple UTXOs of roughly the same size. If you have 10 of those, you will be able to process up to 10 withdrawals concurrently without facing this issue. This is probably the most effective and effortless mitigation.
2. Bundle up all withdrawal requests received in the last 5 minutes or so and issue them at once in a single transaction with multiple recipients.This is a normal procedure of most exchanges to save transaction fees.
3. If a transaction fails at creation, retry after a minute. Well, just in case anything else didn't work.

**Comment by aesedepece** [comment]
@tmpolaczyk @Tommytrg what do you think?

**Comment by tmpolaczyk** [comment]
> As far as I can tell, the wallet doesn't include such protection.

That's false, it's here:

https://github.com/witnet/witnet-rust/blob/f6bcb721d11f6252daff6d72bdea6a385fb7d981/wallet/src/repository/wallet/mod.rs#L1444

The `tx_pending_timeout` variable is defined as "10 epochs". You can easily test this using sheikah, it will not let you create another transaction while a previous one is still pending.

**Comment by aesedepece** [comment]
> That's false, it's here:

Thanks for proving me wrong!

What do you think could be the reason then for the accidental double spend attempt that some exchange saw recently?

**Comment by tmpolaczyk** [comment]
No idea, but this is something that can happen anytime a transaction is stuck for more than 10 epochs, so maybe the fee was too low.

**Comment by aesedepece** [comment]
> No idea, but this is something that can happen anytime a transaction is stuck for more than 10 epochs, so maybe the fee was too low.

That could be the case. They use 1 nanoWit absolute fee, and sometimes there could be miners splitting their UTXOs and paying more than that.

**Comment by aesedepece** [comment]
Marked this as `wontfix 💃` and closing the issue. We can continue discussing if needed.

**Comment by aesedepece** [comment]
> No idea, but this is something that can happen anytime a transaction is stuck for more than 10 epochs, so maybe the fee was too low.

In that case, shouldn't the wallet timely "unmark" / free up the UTXOs from the first transaction?

**Comment by tmpolaczyk** [comment]
* Create transaction when the mempool is full of transactions with higher fee
* Wait 10 epochs
* Create a different transaction, ensure that it uses the same UTXOs as the first one to reproduce the error
* Wait until the mempool has no transactions with higher fee
* Only one of the transactions will succeed, the other will be an error

**Comment by aesedepece** [comment]
@tmpolaczyk can the "ok, this transaction didn't make it to the chain" timeout be configured for the wallet?

**Comment by tmpolaczyk** [comment]
I don't think so, it's hardcoded as `10`, but we can create an issue for that.

**Comment by aesedepece** [comment]
> I don't think so, it's hardcoded as `10`, but we can create an issue for that.

Let's do it. Some user personas may want to raise that timeout considerably.
