### ISSUE TITLE
Allow binding node JSONRPC server to 0.0.0.0

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2288]
The node JSONRPC server can't be currently set to listen on all interfaces (as typically indicated as 0.0.0.0 on POSIX systems.

This is quite a nuisance when a node runs on containers that may change LAN IPs every time they restart, because the configuration will tell it to bind to an address that no longer belongs to any of its networking interfaces.

**Comment by tmpolaczyk** [comment]
Setting

```
[jsonrpc]
server_address = "0.0.0.0:1234"
```

works for me, and it does bind to all the interfaces, so need more info.

**Comment by aesedepece** [comment]
> Setting
> 
> ```
> [jsonrpc]
> server_address = "0.0.0.0:1234"
> ```
> 
> works for me, and it does bind to all the interfaces, so need more info.

I used to believe that `jsonrpc.server_address` didn't allow binding to all interfaces, but maybe I'm mistaken and it was `connections.server_addr` instead?

**Comment by tmpolaczyk** [comment]
Setting `connections.server_addr` to `0.0.0.0:1234` also works, but it has one problem: the node will not know its own IP address, so it won't be able to accept external connections. But we already have the `connections.public_addr` field as a workaround, and the docker script automatically writes the public IP there, so it shouldn't be a big problem.

And another possible problem is that connecting to `0.0.0.0:1234` doesn't work on Windows, you must use `127.0.0.1:1234` instead. But listening on `0.0.0.0` works fine.

**Comment by aesedepece** [comment]
Thanks for the clarification! Closing then!
