### ISSUE TITLE
Setting `RocksDB's "max_open_files" option

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2309]
Our RocksDB integration does not specify a limit for max open files, and hence the library uses `-1` which, surprisingly, does not make RocksDB abide by the limit set in the operating system, but rather pretend that there's no limit and then failing with this horrid error:

`IO error: While open a file for random read: .witnet/storage/057357.sst: Too many open files`

This is a true blocker for running nodes on docker environments where the --privileged flag is not available, or in any serverless / no host context.

It would be great if we could manually set this limit trough `witnet.toml`, as we already do for other RocksDB options, according to this function in the node:

https://github.com/witnet/witnet-rust/blob/6a443bbd097a199db453af589224480ba0326a0d/config/src/config.rs#L1066-L1082

If no limit is set through configuration, I'd advocate for using a best-effort inference of the operating system limit with my beloved [limit-rs](https://crates.io/crates/limits-rs) library.

Only if that best-effort inference fails (e.g. on anything that is not GNU/Linux) I'd resort to the default unlimited behavior.

**Comment by tmpolaczyk** [comment]
> It would be great if we could manually set this limit trough witnet.toml, as we already do for other RocksDB options, according to this function in the node:

Small correction, that logic is only used by the wallet. The node simply uses the default options, by calling the `open_default` function here:

https://github.com/witnet/witnet-rust/blob/2fa9a2fdae4501967d739d9884aaaef1882b02da/node/src/storage_mngr.rs#L370

So as part of this issue we will have to add to the node the functionality to set the same rocksdb options as in the wallet.

**Comment by aesedepece** [comment]
> Small correction, that logic is only used by the wallet. The node simply uses the default options, by calling the `open_default` function [...]

I stand corrected :+1:

**Comment by aesedepece** [comment]
We need this urgently, otherwise operating public nodes on Azure is becoming simply impossible.

**Comment by aesedepece** [comment]
This was solved in #2329
