### ISSUE TITLE
RADON parses JSON integers as floats, rounding them to a different value

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#2315]
So operators like StringParseJSONArray can only parse integers correctly up to MAX_SAFE_INTEGER, which is 2^53-1.

The following test shows how 2^53+1 is parsed as 2^53:

```rust
#[test]
fn test_parse_json_array_max_safe_integer_plus_2() {
    use crate::types::array::RadonArray;
    use crate::types::integer::RadonInteger;
    use crate::types::string::RadonString;

    // 2^53 + 1
    let input = RadonTypes::from(RadonString::from(r#"[9007199254740993]"#));
    let script = vec![(RadonOpCodes::StringParseJSONArray, None)];

    let output = execute_contextfree_radon_script(input, &script).unwrap();

    assert_eq!(
        output,
        RadonTypes::from(RadonArray::from(vec![RadonTypes::from(RadonInteger::from(
            9007199254740993
        ))]))
    );
}
```

Output:

```
thread 'script::tests::test_parse_json_array_biggish_integers' panicked at 'assertion failed: `(left == right)`
  left: `Array(RadonArray { value: [Integer(RadonInteger { value: 9007199254740992 })], is_homogeneous: true })`,
 right: `Array(RadonArray { value: [Integer(RadonInteger { value: 9007199254740993 })], is_homogeneous: true })`', rad/src/script.rs:607:9
```

**Comment by guidiaz** [comment]
Could we set the Json parser lib to use quadruple precision floats instead ?

**Comment by aesedepece** [comment]
> [...] Or to only convert into double floats when there's a decimal dot and to an integer when there's not ?

I believe that's what it's supposed to do :thinking:

**Comment by tmpolaczyk** [comment]
Yes, it converts to integer, but it converts the float to integer, therefore losing precision:

https://github.com/witnet/witnet-rust/blob/0807e050a4906dc302a8ddf263d9fe53d0becddb/rad/src/operators/string.rs#L249-L260

The `Number` type used by the JSON parsing library is some weird emulated floating point type with 64 bit mantissa and 16 bit exponent, so maybe it is possible to support 64-bit integers using that library.
