### ISSUE TITLE
Stop using surf as http client

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#2335]
When trying to prototype #2331, we have noticed that the surf client does not properly support HTTP HEAD requests. That issue has been reported on the surf repo more than two years ago, but it has not been fixed yet, even though it looks like a simple fix. And there are similar issues and FIXMEs in witnet-rust regarding surf issues, such as url parsing for example. Also, the last commit on the surf repo is from May 10, 2022, and it doesn't look very active anymore. Therefore it seems reasonable to stop using surf as a dependency.

Fortunately, we now have a witnet http client implemented here: https://github.com/witnet/witnet-rust/blob/11d37d32c6caa3965d716854beae728867c5ce70/net/src/client/http/mod.rs#L1

That client is a wrapper over the isahc http client, of which surf is also a wrapper. So it should be straightforward to add the missing API there, and drop the dependency on surf. And since we will still be using isahc under the hood, this should be a minor change, and it shouldn't break any requests.

**Comment by aesedepece** [comment]
This is a good idea. From what I remember when implementing the paranoid retrieval mode, it could save us as a lot of boilerplate around error types, etc.

**Comment by aesedepece** [comment]
Solved by #2399
