### ISSUE TITLE
Implement real method for checking PoE in ReputationManager

### ISSUE THREAD

**Issue by anler** [witnet/witnet-rust#235]
Implement real method for checking PoE (Proof of Eligibility) in `ReputationManager` actor. Currently it always assumes it is valid, see #228.

**Comment by tmpolaczyk** [comment]
The `ReputationManager` should have a method to check the PoE from past blocks, for example when a node connects to the network and requests several blocks at once, the reputation will not be the same for all the blocks.

**Comment by aesedepece** [comment]
The reputation set is updated from looking at the chain, just like the unspent transaction output set. There's no need to revisit past block (and thus snapshots of previous states of those sets) because synchronization is linear.

**Comment by tmpolaczyk** [comment]
Alright, then we just need to make sure that synchronization is linear: verify the blocks in order and put the pending blocks in some sort of queue.

**Comment by tmpolaczyk** [comment]
Already implemented
