### ISSUE TITLE
Create blocksPool data structure in ChainManager's state

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#237]
The `blocksPool` data structure in `ChainManager`'s state will hold multiple entries of this shape:
```rust
(block, transactionsPool, unspentOutputs)
```
_Suggestion: entries should be accessible by block hash, so the data structure may be a `HashMap`_.

Explanation of each element:
- __block__: a block candidate for Epoch _e_.
- __transactionsPool__: a snapshot of `ChainManager.transactionsPool` at checkpoint _e_.
- __unspentOutputs__: a snaptshot of `ChainManager.unspentOutputs` at checkpoint _e_.

**Comment by anler** [comment]
As we have discussed, since we are following the _best candidate_ block strategy, having a pool of blocks doesn't seem to be that useful at the moment. Closing this issue.
