### ISSUE TITLE
`getBalance` node JSONRPC method ignores `simple` positional argument

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2390]
https://github.com/witnet/witnet-rust/blob/ad46722c2a67ebedab679751ca17939f49d30cb6/node/src/actors/json_rpc/api.rs#L1305-L1324

Thanks to @Tommytrg for reporting.

**Comment by aesedepece** [comment]
`simple = params.get(1).or(false)`

**Comment by Tommytrg** [comment]
Closed by #2395
