### ISSUE TITLE
Create AddTransaction handler in ChainManager for processing transactions

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#240]
When a `Transaction` is received through the `TRANSACTION` handler in `Session`, it should be sent to `ChainManager` through an `AddTransaction` actor message (see #233).

Then, the `AddTransaction` handler should:
1. check that the all the inputs point to unspent outputs found in our `unspentOutputsPool`,
2. take all those unspent outputs and sum their values,
3. sum the values of all the outputs in the transaction we are processing and check if it is less than the result of the previous step,
4. run the WitScript of the up-until-now-unspent outputs and the inputs trying to spend them, combined together, and check if the result is `true` and the stack is left empty for all of them,
5. push the transaction into `transactionsPool`.

If any of the mentioned validations fail, the transaction is just forgotten.

**Comment by Tommytrg** [comment]
Closed by #290
