### ISSUE TITLE
Create unspentOutputsPool data structure in ChainManager's state

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#244]
The `unspentOutputsPool` data structure is Witnet's equivalent of Bitcoin's `UTXO set`. That is, a list of all the outputs available for being spent.

The `UTXO` model implies that _your coin balance is the summation of the values enclosed in every transaction output encumbered by a set of spending conditions that you can satisfy_.

Under this model, every transaction anchored to a block mutates the `unspentOutputPool` by removing the outputs to which its inputs point to and by pushing its own outputs into it.

As for the specific shape of the `unspentOutputPool` data structure, a `HashMap` like this should work:
```json
{
  "<transaction hash>": {
    "<output index>": "<the complete output itself>"
  }
}
```
E.g.
```json
{
  "EADA0022EAC9EEBCCC4D07DC82C23A90C4BBD5B0E1F3A2F1CE4B29C93CD769BA": {
    "0": {
      "value": 500,
      "spendingConditions": "74686973206973206E6F74206120736372697074",
    }
  }
}
```

**Comment by anler** [comment]
My 2 cents:

I agree with @mariocao and I prefer  `HashMap<transaction_id || output_index, Output>` better than two nested hash tables, but! this solution will cause the table to have a lot more keys (will consume more space) and it'll make difficult some operations like: _give me all the outputs for this transaction id_

There's another approach I can think of though:

```rust
type Outputs = Vec<Output>;
type UTXOSet = HashMap<Hash, Outputs>;
```

which is similiar to the two nested hash tables approach, but takes advantage of the O(1) indexing operation of the vector, it will consume less space than the approaches above, but accessing an output won't be as fast as the `HashMap<transaction_id || output_index, Output>` solution.
