### ISSUE TITLE
Make a list of wit/2 remainders

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2470]
I started working on a list of everything that is broken, missing or lacking in the wit/2 branches.

This issue will track the completion and publication of such list, and will host the discussion on where to draw the line between what falls into the first witnet-rust 2.0 release candidate and what's left for subsequent release candidates to be released while already in testnet phase.

**Comment by drcpu-github** [comment]
Here is a list of items which I think are required for the Witnet 2.0 release:
- [ ] A way to handle data requests which require too many witnesses. This can either be [refusing to include such a data request in a block](https://github.com/witnet/witnet-rust/pull/2444) or [creating a Tally with an error](https://github.com/witnet/witnet-rust/pull/2446).
- [ ] A way to track [active validators](https://github.com/witnet/witnet-rust/pull/2448). In my opinion this is absolutely required to prevent griefing attacks where an attacker would purposely stake on inactive validator addresses to disrupt superblock consensus. I also think somehow using this active validator set would improve data request processing or even block proposals.
- [ ] An easy way to check the withdrawer associated with a validator for easier staking transaction validation.

Ideas for a Witnet 2.1 release:
- [ ] Implement a slashing mechanism for nodes that are not voting on a superblock. Slashing should probably only happen when there is no superblock consensus.
