### ISSUE TITLE
Make a final decision on block time and block reward

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2474]

**Comment by Tommytrg** [comment]
We have multiple proposals in the table. The values in the [initial issuance draft](https://github.com/witnet/WIPs/pull/101) don't match the ones in [DrCpu's PR](https://github.com/witnet/witnet-rust/pull/2472). We have to make a decision on block reward and block time and adapt the WIP or the PR accordingly.

**Comment by drcpu-github** [comment]
Just want to reiterate that the 50 WIT I added in that PR is nothing but a placeholder based on some rough numbers I put in a spreadsheet (see https://github.com/witnet/WIPs/pull/101#discussion_r1643395979). I assumed neither the issuance draft where it mentions 125 WIT / block nor my PR had to be considered as a final decision.

**Comment by aesedepece** [comment]
You all know that a few months ago [I voiced my support](https://github.com/witnet/WIPs/pull/101#discussion_r1555833245) for a near immediate inflation reduction (or be equivalent to accelerating a halving, if you want to see it that way), but that I was reluctant at the time to take the initiative to champion that change and put it in a WIP on my name, because of conflict of interests.

However, at this point, as the numbers presented in [drcpu's table](https://github.com/witnet/WIPs/pull/101#discussion_r1643395979) make quite a lot of sense to me under the perspective of achieving a competitive APY, nobody else in the community has voiced any opposition to such change, and the fact that existing stakeholders would be pleased by any issuance rate reduction measures, I can now confidently take a step forward and adopt that proposal or one that produces a similar effect.

**Comment by drcpu-github** [comment]
Just for the sake of adding some more data, I actually ran [a poll](https://t.me/witnetio/122116) regarding inflation in wit\2 on Telegram. This is a snapshot of the poll:

![inflation_reduction_poll](https://github.com/witnet/witnet-rust/assets/65105305/5e1e4ef3-2abc-4e90-bd58-3dfb0b63fa59)
19 people voted for reduction, 11 people voted for a high APR (keeping the current inflation). With 30 votes on that poll and a solid 63% in favor of inflation reduction, I'd say a proposal following that result is fair game.

**Comment by aesedepece** [comment]
A quick look at crypto staking explorers shows that for top staking protocols in 2024:
- Reward rate (aka APY/APR) ranges 1-19% and averages 8.5%
- Staking ratio ranges 23-81% and averages 55%

Translating that into the wit/2 realm, for a first year of staking:
| Issuance per minute | RR(SR=23%) | RR(SR=55%) | RR(SR=81%) |
|-----------|-------------|-------------|-------------|
| 150 Wit     | 24.84%      | 10.39%      | 7.05%       |
| 225 Wit     | 37.26%      | 15.58%      | 10.58%      |
| 300 Wit    | 49.68%      | 20.77%      | 14.11%      |

Looking at these numbers, it becomes evident than the 150 Wit/minute proposal (namely, 50 Wit every 20 seconds) is indeed the one that is the most in line with the current staking market.

**Comment by aesedepece** [comment]
150 Wit/minute (50 Wit every 20 seconds) seems to be the consensus here. Let's move on!
