### ISSUE TITLE
Make sure that GitHub actions can produce builds with suffixes

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2483]
In order to compile and publish the release candidate for witnet-rust 2.0, we need to make sure that GitHub actions can produce builds with suffixes, i.e. have versions in the likes of `2.0.0-rc1`.

**Comment by Tommytrg** [comment]
We need to apply the following changes to be able to produce builds with suffixes:
- [ ] [Update regex in subcrate's comparison](https://github.com/witnet/witnet-rust/blob/master/.github/actions/versions-match/action.yml)
- [ ] Update Github actions versions
- [ ] Update deprecated CI libraries
