### ISSUE TITLE
Update consensus constants for Wit/2

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2499]
We need to make sure that consensus constants (and pseudo consensus constants) have the right values for Wit/2.

**Comment by drcpu-github** [comment]
https://github.com/witnet/witnet-rust/pull/2497/commits/17aa17ff6a93101fc3d154378fd787e1d07de27b

**Comment by aesedepece** [comment]
Solved in 17aa17ff6a93101fc3d154378fd787e1d07de27b. Thanks Doctor!
