### ISSUE TITLE
Revisit implementation of Validators Slashing

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-rust#2543]
.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-rust/2543?planning-poker) with Zenhub @aesedepece @aeweda @gabaldon @guidiaz

**Comment by aesedepece** [comment]
> https://hackmd.io/4lWATsuiREWKWxK9Uh-DyQ

knock knock still can't access
