### ISSUE TITLE
Stakes can't be snapshot and rolled back

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#2544]
Unlike all other fields in `ChainState`, `stakes: Stakes<_>` can't be snapshot and rolled back. That is, it doesn't freeze its state because of its heavy reliance on reference counts and write counts.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-rust/2544?planning-poker) with Zenhub @aesedepece @aeweda @gabaldon @guidiaz

**Comment by aesedepece** [comment]
Solved by #2548
