### ISSUE TITLE
Update `queryStakes` JSONRPC method to support staking in different applications

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#2552]
To support staking in myWitWallet and other libraries, the `queryStakes` JSONRPC method needs to support the following features:
- Include the nonce in the response to facilitate the unstaking process.
- Instead of returning only the total staked amount, `queryStakes` should return a map with two keys:
  - `total`: The total staked amount.
  - `stakes`: An array of stake objects filtered by the specified parameter (`withdrawer`, `validator`, or `stakeKey`).

To keep the JSONRPC and the CLI consistent, the changes should also be applied to the CLI method. 

Issue related with https://github.com/witnet/my-wit-wallet/issues/618.

**Comment by aesedepece** [comment]
>       * `total`: The total staked amount.
The total might be irrelevant depending if we query by `withdrawer`, `validator`, or `stakeKey`. I'd leave it out and stick to just returning a vector of stake entries, with their corresponding keys, amounts and nonces. Calculating the total on the client side—when it makes sense—is trivial.
