### ISSUE TITLE
Change purpose of `epoch_to_block_hash` map in ChainManager 

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#295]
As discussed in #292:

> currently we store the block candidates in the storage, and it shouldn't be that way. The `epoch_to_block_hash` should store only consolidated blocks, and a new structure would keep the block candidates (and discard candidates from old epochs?).

Bottom line:
- `epoch_to_block_hash` is supposed to map checkpoint numbers to the digest of the best block in the subsequent epoch
- `epoch_to_block_hash` is thus bound to be useful as a linear representation of the block chain
- `epoch_to_block_hash` is a persisted collection (see #293 and #294)
- Thus, block candidates shouldn't be present in `epoch_to_block_hash`
- If block candidates happen to need such mapping (because of slow validations), we can have a separate mapping.
- We can rename `epoch_to_block_hash` to just `block_chain`. Elegant, right?

**Comment by aesedepece** [comment]
@mariocao Up to what point does #309 solve or invalidate this issue?

**Comment by tmpolaczyk** [comment]
Fixed in #373
