### ISSUE TITLE
Add addresses from inbounds as potential outbounds

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#298]
As for `testnet-1`, in order to facilitate peer discovery, improve the network's "meshness" and introduce some resilience to faulty or come-and-go nodes, we may change our current potential peer address recollection strategy.

Every time we consolidate an inbound session, we can push the peer's address into `PeerManager` through the `AddPeers` command.

**Comment by mariocao** [comment]
As discussed with @aesedepece , this issue can be considered as closed as the described functionality is already implemented, i.e. IP addresses from inbound peers are added through the PeersManager.
