### ISSUE TITLE
`Broadcast<WitnetMessage>` should route message to all consolidated sessions, not only outbounds

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#308]
`Broadcast<WitnetMessage>` should route the message to all consolidated sessions, not only outbounds.

Otherwise, your inbounds would only get your transactions and blocks if they are connected to you through a different, indirect route of subsequent outbounds in the graph. This is not guaranteed at alll, which in practice means that in insufficiently large and meshed networks a high percentage of blocks will not reach a majority of the network and forks will happen often.

Propagation time using this strategy will be reduced drastically and it this will increase the chances for a block to reach every node in a timely manner, thus making consensus easier and safer.

**Comment by tmpolaczyk** [comment]
Fixed in #476.
Now to is possible to choose between Broadcast to all consolidated sessions, or only consolidated inbound sessions with the `only_inbounds` flag.
