### ISSUE TITLE
Serializers implementation

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#32]
#### Description
Witnet-rust will use [Flatbuffers](https://google.github.io/flatbuffers/index.html) as serialization library, but, in spite of this, it is not discarded support other similar libraries in future. Because of that, the first approach will create a "serialization"/"codecs" folder where to implement methods as ```fromX``` and ```toX``` for a concrete library and manage which one should be used at compilation time.

Focusing on the point of view of a peer: ***as a peer, I want to be able to create a structure\* where add a message object that could be read from other peers.***

\* *A structure which uses flatbuffers in a first approach*

#### Actionables
- [ ] Define an API to wrap flatbuffers' native methods.
- [ ] Implement serializer methods of flatbuffers.
- [X] Define Flatbuffers schema.
- [ ] Define schema's message types mirroring flatbuffers ones.
- [X] Implement flatbuffers schema.
- [ ] Use flatbuffers ```verify``` from C library.

**Comment by mariocao** [comment]
I created #69 in order to track the optional task/issue described in the actionables of this issue. :blush:
