### ISSUE TITLE
Make inventory syncing reactive, not periodic

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#388]
Inventory syncing is performed in periodic batches of up to 250 items. This period is tied to the checkpoint period, which is 90 seconds. This introduce unnecessary latency yet it doesn't account for batches that take more than 90 seconds, thus causing those blocks to be discarded and then queried again short after.

We should make inventory syncing reactive, that is, querying the next batch as soon as we have finalized validating and consolidating the previous one.

**Comment by tmpolaczyk** [comment]
Fixed in #476. The synchronization strategy has been improved, it is now reactive.
