### ISSUE TITLE
Wallet API design

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#405]

**Comment by Tommytrg** [comment]
As a result of this discussion we decided that the wallet should expose an API with de following methods:
- get_wallet_infos() -> Vec\<WalletInfos>
- create_mnemonics() -> Mnemonics
- import_seed(mnemonics / xpriv) -> ()
- unlock_wallet(id, password) -> Wallet
- get_transaction(wallet_id, limit, page) -> Vec\<Transaction>
- send_vtt(wallet_id, to_address, amount, fee, subject) -> Transaction
- generate_address() -> Address
- create_data_request(data_request_args) -> DataRequest
- run_data_request(data_request) -> RadonValue
- send_data_request(data_request) -> ()
- lock_wallet(wallet_id, wipe=false) -> ()
