### ISSUE TITLE
Build `darwin` binary

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#416]

**Comment by burguesia** [comment]
To compile for macOS:

$ curl https://sh.rustup.rs -sSf | sh
$ rustup default stable
$ rustc --version
$ source $HOME/.cargo/env
(if you don't have clang install it by running $ xcode-select --install)
$ pip install FoLiA-Linguistic-Annotation-Tool
$ git clone https://github.com/witnet/witnet-rust.git
$ cd witnet-rust
$ git checkout 0.1.1
$ cargo build --release

**Comment by aesedepece** [comment]
Now ProtoBuf may be necessary as well:
```
# brew install protobuf
```
