### ISSUE TITLE
Fix some inconsistencies between schema and documentation

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#423]
- [ ] ValueTransferOutput: missing time_lock field
- [ ] Version: genesis should be a Hash
- [ ] InventoryEntry: DataRequest and DataResult are not used, should be removed

**Comment by aesedepece** [comment]
Structure documentation is deprecated (too hard to maintain). For what it's worth, the schema shall be considered the standard for the protocol.
