### ISSUE TITLE
Witnet node should create a default config file (if not present)

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#427]
When running the Witnet node without having a configuration file (`witnet.toml`), then a panic occurs.
Some suggestions to address the problem:
 - Create default config file and use it
 - Use default configuration without creating config file
 - Abort node initialization and prompt some error (instead of panicking because an unwrap)

**Comment by aesedepece** [comment]
I'm totally for the second suggestion and against the first (we have no guarantees that `cwd` is writable).

**Comment by anler** [comment]
The solution I have opted for in #434 is:
- If user does not specify a config file in the command line, the default is used
- If user does specify a config file in the command line, and that file doesn't exist or can't be read, the application stops

**Comment by tmpolaczyk** [comment]
Fixed in #434
