### ISSUE TITLE
Define configuration data structure

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#47]
Define the required configuration parameters that are currently needed, including the following:

 - Connections configuration
   - server address (IP and port)
   - limits for outbound and inbound connections
   - list of known peers to connect
 - Storage configuration (database path)

Tasks:
- [x] Define config struct
- [ ] Document configuration data format

**Comment by anler** [comment]
This is my proposition on how the configuration struct should look like:

```rust
pub struct Config {
    pub server: ServerConfig,
    pub client: ClientConfig,
    pub storage: StorageConfig,
}

pub struct ServerConfig {
    pub socket_ip_addr: net::IpAddr,
    pub socket_port: u16,
    pub peers_limit: u16,
}

pub struct ClientConfig {
    pub peers_limit: u16,
}

pub struct StorageConfig {
    pub db_path: path::Path,
}
```

That is, the main configuration is composed of sections, where each section is composed of properties.

**Comment by mariocao** [comment]
After discussing it with @mmartinbar , here are our comments:
 - Array of known peers is missing
 - Naming to be coherent with rest of code (inbound/outbound instead of server/client)
 - (Optional) use of SocketAddr (because we already need it for the list of known peers)

Our suggestion:
```rust
pub struct ConnectionsConfig {
    pub server_addr: SocketAddr
    pub inbound_limit: u16,
    pub outbound_limit: u16,
    pub known_peers: Vec<SocketAddr>,
}
```

What do you think? :smiley_cat:
