### ISSUE TITLE
Assess subscription in WS server

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#500]
Assess how to implement client subscriptions with the `Wallet`.

**Comment by tmpolaczyk** [comment]
The [jsonrpc-pubsub](https://crates.io/crates/jsonrpc-pubsub) crate provides support to subscriptions, and it is compatible with [jsonrpc-ws-server](https://crates.io/crates/jsonrpc-ws-server).

So now both the node and the wallet use the `jsonrpc-pubsub` crate for subscriptions, however there is still some code duplication.

The wallet is able to forward subscriptions to the node, and then forward the notifications from the node to the client. The subscription names are hardcoded, so when adding new subscription methods to the node, they should also be added to the wallet.

For future work, it would be nice to extract the common code somehow, but it should not be a priority.

See the implementation in #534
