### ISSUE TITLE
Define wallet API errors

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#532]
Define which errors could send each method of the wallet API

**Comment by Tommytrg** [comment]
According with the [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification#error_object), code errors are:

| Code    | Message | Meaning  |
| --------- | ----------- | ------------- |
| -32700 | Parse error | Invalid JSON was received by the server. An error occurred on the server while parsing the JSON text. |
| -32600 | Invalid Request | The JSON sent is not a valid Request object. |
| -32601 | Method not found | The method does not exist / is not available. |
| -32602 | Invalid params | Invalid method parameter(s). |
| -32603 | Internal error | Internal JSON-RPC error. |
| -32000 to -32099 | Server error | Reserved for implementation-defined server-errors. |

Because of that we should define error codes in the range [-32099, -32000] _reserved for implementation-defined server-errors_

**Comment by tmpolaczyk** [comment]
That is the range for server errors, user defined errors can be whatever you want.

For example, in ethereum, an error code of 102 means "gas too low":
https://github.com/ethereum/wiki/wiki/JSON-RPC-Error-Codes-Improvement-Proposal

**Comment by Tommytrg** [comment]
We could use the range [100, 200) for [rad errors](https://github.com/witnet/witnet-rust/blob/master/rad/src/error.rs#L8) codes. So I propose the following: 

| Code    | kind |
| --------- | ------ |
| 100 | Decode |
| 101 | Encode |
| 102 | Hash |   
| 103 | Http |
| 104 | JsonParse |
| 105 | MapKeyNotFound |
| 106 | MessagePack |
| 107 | NoOperatorInCompoundCall | 
| 108 | NotIntegerOperator |
| 109 | NotNaturalOperator |
| 110 | ParseFloat |
| 111 | ScriptNotArray | 
|112 | UnknownOperator |
|113 | UnsupportedHashFunction |
|114 | UnsupportedOperator |
| 115 | UnsupportedReducer |
|116 | WrongArguments |

**Comment by tmpolaczyk** [comment]
Why would we need separate JSON-RPC error codes for RAD errors? The result of a data request can be an error, that's expected, so the JSON-RPC response would just be a success response where the result is an encoded `RadError`.

But maybe I am misunderstanding something because I don't see where the `RadError` is serialized to MessagePack.

**Comment by anler** [comment]
I have opened #660 with the following proposal taking into account @tmpolaczyk recommendations:

## Custom Error Codes

| Code      | Error           | Description                                                                  |
| --------- | ------          | ------                                                                       |
| 1         | Execution error | There was an internal error. The data field will contain additional details. |
| 2         | Node error      | There was an error when communicating with the node.                         |

## Execution Error

The execution error will contain additional error fields in the `data` attribute to further explain what went wrong. So far there's only [one catch-all case defined](https://github.com/witnet/witnet-rust/pull/660/files#diff-a699cba0eb4a455e541af773eec08be8R33):

| Code      | Error         | Description                                          |
| --------- | ------        | ------                                               |
| 100       | Generic Error | There an error.                                      |

The idea is to augment this list with the error codes we find useful.

**Comment by anler** [comment]
Issue implemented in #660 

## Custom Error Codes

| Code      | Error           | Description                                                                  |
| --------- | ------          | ------                                                                       |
| 1         | Execution error | There was an internal error. The data field will contain additional details. |
| 2         | Node error      | There was an error when communicating with the node.                         |

## Execution Error

The execution error will contain additional error fields in the `data` attribute to further explain what went wrong. So far there's only [one catch-all case defined](https://github.com/witnet/witnet-rust/pull/660/files#diff-a699cba0eb4a455e541af773eec08be8R33):

| Code      | Error         | Description                                          |
| --------- | ------        | ------                                               |
| 100       | Generic Error | There was an error.                                      |

The idea is to augment this list with the error codes we find useful.

**Comment by aesedepece** [comment]
I'm reopening this because of https://github.com/witnet/sheikah/issues/594
