### ISSUE TITLE
Define the state of the sessions manager actor

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#55]
The `Sessions Manager` actor needs to manage sessions (both inbound and outbound) and their different states (consolidated/unconsolidated). For that purpose, the state of the `Sessions Manager` actor needs to store them in some way.

At the moment, the `Sessions Manager` stores the inbound and outbound sessions into two different hashmaps, being the key the session id and the value the address of the session actor. This needs to be changed so that the sessions manager can distinguish sessions by their state.

Tasks:
- [x] Assess different possible session states
- [x] Define and implement the required data structures in the session manager state
- [x] Update doc accordingly

**Comment by mariocao** [comment]
Closed by #63
