### ISSUE TITLE
Support Raspberry Pi 2 and Pi 3

### ISSUE THREAD

**Issue by joesixpack** [witnet/witnet-rust#552]
Please provide release binaries for Raspberry Pi 2 (ARMv7) and Raspberry Pi 3 (ARMv8, both AArch32 and AArch64) or proper directions to cross compile from source to such on desktop as I don't think there's enough memory to fully build the initial "cargo run node" on the Pi 3 (Debian 9/10 aarch64).  Keeps rebooting on 331/332: witnet(bin).

**Comment by aesedepece** [comment]
Hey @joesixpack, thanks for posting the issue!

We are currently providing binaries for the `armv6l` architecture, which afaik should work on all Raspberry Pi models. [Here's the download page][release].

I will definitely give a look to the possibility to transcompile, which may save us some time when producing releases as right now we need to trigger a remote job on an actual RasPi.

Btw, I'm shocked to hear that your Pi 3 keeps rebooting upon compiling `witnet-rust`. It worked for me everytime on a 2016 Pi 3B (the original, not the plus) and on a Pi Zero W, which is much more limited. Sorry if what I'm suggesting sounds silly, but is it possible that you are not giving enough power to your RasPi? I used to have reboot problems many times in the past when powering RasPis with the typical 0.5A or 1A USB adapters that everyone has plenty around. 2A "fast-charge" adapters are the way to go.

[release]: https://github.com/witnet/witnet-rust/releases/latest

**Comment by joesixpack** [comment]
When I tried the armv6l binary, the Pi 3 would not recognize it at all.  
I'm assuming because its an arm32 binary and not arm64 (I don't think 
armv6l was 64-bit anyway).

I do have an upgraded power supply, 2.5A including a heat sink and fan.

**Comment by aesedepece** [comment]
Thanks for the insights @joesixpack.

I'll give a try to the [cross crate], which provides convenient cross compilation for `armv7-unknown-linux-gnueabihf` or `aarch64-unknown-linux-gnu`, which you seem to be using. 

Will keep you updated.

[cross crate]: https://github.com/rust-embedded/cross

**Comment by aesedepece** [comment]
I have cross compiled `witnet-rust` for the all the 3 ARM architectures used by different Raspberry Pi models:
- `arm-unknown-linux-gnueabihf`: armv6, Raspberry Pi 1 and Zero, 32 bits
- `armv7-unknown-linux-gnueabihf`: armv7, Raspberry Pi 2 and 3, 32 bits
- `aarch64-unknown-linux-gnu`: armv8, Raspberry Pi 3, 64 bits

These are already available to download in [the releases page][releases] and I will post tomorrow a PR with all the instructions and tools for producing your own cross compiled build on your own.

[releases]: https://github.com/witnet/witnet-rust/releases/latest
