### ISSUE TITLE
Support cross compiling `darwin` binaries from `x86_64-linux-gnu` hosts

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#564]
In the line of #552 / #562 (ARM cross compilation), we should be able to cross compile `witnet-rust` for `darwin` from any `x86_64-linux-gnu` machine.

Here are some hints on how to make it work:
- https://github.com/japaric/rust-cross
- https://www.reddit.com/r/rust/comments/6rxoty/tutorial_cross_compiling_from_linux_for_osx/
- https://www.reddit.com/r/rust/comments/2vhi3w/crosscompiling_stdlib_for_x86_86appledarwin/
- https://gist.github.com/luser/a33e5070d1c55a7d2c46fe763a9d1543
- https://github.com/multiarch/crossbuild

**Comment by Tommytrg** [comment]
As a workaround for this issue, we'll implement #2107
