### ISSUE TITLE
Print master public key upon generation / loading

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#566]
It'd be nice to have the master public key printed to the logs when it gets generated or loaded when the node starts.

Ideally, the public key should be presented in two different formats:
- `ypub`, using [`slip32`](https://github.com/satoshilabs/slips/blob/master/slip-0032.md) and [`slip132`](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) with prefix `wpub` / `wtpub`.
- `bech32` serialization of 20 first bytes of public key hash (a.k.a. _address_).

**Comment by aesedepece** [comment]
Currently the `bech32` serialization of 20 first bytes (address / pkh) is already being printed upon every start of the node.

**Comment by mariocao** [comment]
Already implemented!
