### ISSUE TITLE
Implement sessions manager messages and handlers

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#57]
The sessions should be able to handle incoming messages in order to manage sessions, i.e.:

- register a new session, given an address and a reference to the session actor
- update an existing session, given an address and a new session status
- unregister an existing session, given an address

Tasks:

- [x] Handler for the /register session message
- [x] Handler for the /update session message
- [x] Handler for the /unregister session message
- [x] Documentation of the session manager

**Comment by mariocao** [comment]
Closed by #63
