### ISSUE TITLE
High-level transaction factory

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#570]
We need a way to create transactions without having to manually add the utxos and the signatures. The node should keep track of all its mint transactions from mined blocks, and use them as inputs to value transfer transactions and data requests.

The API should be similar to:

```rust
fn build_vtt(vto: ValueTransferOutput) -> Transaction {}
fn build_drt(dro: DataRequestOutput) -> Transaction {}
```

**Comment by aesedepece** [comment]
This is a dead simple snippet for selecting UTXOs that I wrote in Elixir long ago:
```elixir
def take_enough_utxos(my_utxos, amount) do
  Enum.reduce_while(my_utxos, {0, []}, fn (utxo, {acc, list}) ->
    acc = acc + utxo.value
    list = [utxo | list]
    if acc >= amount do
      {:halt, {acc, list}}
    else
      {:cont, {acc, list}}
    end
  end)
end
```
It will give you a list of UTXOs that sum up enough value to satisfy the required `amount`, along the actual sum of their value, which is exactly the value for the _change output_ pointing back to a PKH from our own wallet.

This assumes that:
- `amount` includes the desired fee
- `my_utxos` is somehow ordered by value
