### ISSUE TITLE
Improve protocol decoding error messages

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#587]
When we fail to decode protocol mesages (likely because we tried to peer with someone using a different protocol schema), the error messages are not helpful at all:
```
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(8406))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(UnexpectedWireType(WireTypeStartGroup))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(7))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(55))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(70))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(UnexpectedWireType(WireTypeStartGroup))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(12558))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(14334))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(3))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(UnexpectedEof)
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(4))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(22))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(IncorrectTag(46))
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(UnexpectedEof)
[ERROR witnet_node::actors::session::handlers] Error decoding message: WireError(UnexpectedWireType(WireTypeStartGroup))
```
Ideally, we should be able to map these errors into something more helpful like:
```
[ERROR witnet_node::actors::session::handlers] Error decoding protocol message of type `GetPeers`
[DEBUG witnet_node::actors::session::handlers] ├── ProtoBuf error was: "WireError(UnexpectedEof)"
[TRACE witnet_node::actors::session::handlers] └── Bytes were: [0, 0, 0, 0, /* ... */]
```
___
**This issue is marked as a [good-first-issue](https://github.com/witnet/witnet-rust/labels/good%20first%20issue%20%F0%9F%91%8B)**. If you need help solving this, feel free to ping its assigned menthor: @aesedepece

**Comment by gil-air-may** [comment]
Is there a way to run the node without getting this error?

**Comment by aesedepece** [comment]
@gil-air-may you can run two nodes locally with different configuration files. They will need to have each other's address and port as their only peer address in `KNOWN_PEERS`. Here's the [Witnet-rust configuration documentation][docs] for reference.

Making a node peer with itself (by putting its own address and port into `KNOWN_PEERS`) may work too.

In either case, make sure to remove the default `40.121.131.135` IP address, which belongs to our public bootstrapping node. Peering with that node using the master branch is what causes the error, as the changes landing with version 0.2.1 will not be backwards compatible.

[docs]: https://docs.witnet.io/configuration/toml-file/

**Comment by aesedepece** [comment]
I'm self-assigning mentorship for this issue.

**Comment by pawanjay176** [comment]
I would like to work on this issue. How do I recreate the error log?

**Comment by aesedepece** [comment]
@pawanjay176 thanks for your interest and welcome to the Witnet community!

To reproduce this issue, just run the node with `cargo run node` and wait a few seconds for it to try to download blocks from the current testnet's bootstrapping node.

**Comment by pawanjay176** [comment]
@aesedepece Can you guide me a little on how to approach this? I tried running err.cause() assuming it would destructure the error in `handle` function in `src/actors/session/handlers.rs` but it just returns the full error.

**Comment by aesedepece** [comment]
@pawanjay176 You are right, at a closest look to the code, it looks impossible to obtain the type of the message without doing crazy stuff with the bytes.

Let's rather try to do it like this:
```
[ERROR witnet_node::actors::session::handlers] Error decoding protocol message
[ERROR witnet_node::actors::session::handlers] ├── ProtoBuf error was: "WireError(UnexpectedEof)"
[DEBUG witnet_node::actors::session::handlers] └── Bytes were: [0, 0, 0, 0, /* ... */]
```

Which means that you don't need to destructure the error at all :wink:

**Comment by pawanjay176** [comment]
@aesedepece  So basically I have to add the extra debug lines in the `handle` function right?
```rust
match result {
    Err(err) => {
        error!("Error decoding protocol message");
        error!("|── Protobuf error was: {:?}", err.to_string());
        error!("|── Bytes were: {:?}", bytes.as_ref());
    },
...
```
I'm a bit confused regarding the commit message standards though. Would this come under `docs`?
