### ISSUE TITLE
Define and document all possible RADON errors

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#630]
For the sake of consensus across potentially multiple RADON implementations, errors thrown by the different operators should be duly standardized and documented.

**Comment by aesedepece** [comment]
They are already defined, but missing documentation.

**Comment by mariocao** [comment]
Issue moved to [witnet/documentation #70](https://github.com/witnet/documentation/issues/70) via [**ZenHub**](https://www.zenhub.com/)
