### ISSUE TITLE
Validate RaPoE

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#655]

**Comment by tmpolaczyk** [comment]
PR #651 leaves a few FIXMEs related to this issue.

This needs to be done:

* Calculate the target hash as `[0xFF; 32] / num_active_identities`
* Don't mine blocks if the vrf proof hash does not meet the target hash
* Add block miners to the `ActiveReputationSet`, they can be identified by the `PublicKey` in `BlockEligibilityClaim`
