### ISSUE TITLE
Ignore, forbid and punish sending unsolicited `Peers` messages

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#739]
Currently, `inbound` peers could send `PEERS` message to other nodes, which automatically add them to their peer list.
This could be use to poison the `new peers` bucket.

The impact of this attack should not be too high because of the countermeasures provided by the `feeler` mechanism.

**Comment by tmpolaczyk** [comment]
Merged in #1626 as commit 128e9705049b79982f59740c4122515d7e38c725
