### ISSUE TITLE
Refactor bridge

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#772]
- Discussion about new bridge architecture design
- FIX: Channel closes in case of an error is produced in the "and_then castle" in bridges/ethereum/src/main.rs, and bridge fails
- Review non specific naming
- Show errors to ease its handling. Most of them are mapping to ()
- Use functions inside closures to ease code review
- Promote closures that dispatch actor messages to named functions

**Comment by aesedepece** [comment]
Is this 100% addressed by #722 or do we need a separate issue for any leftovers?

**Comment by tmpolaczyk** [comment]
Yes, this was addressed by #722, closing.
