### ISSUE TITLE
RocksDB issues in the wallet

### ISSUE THREAD

**Issue by anler** [witnet/witnet-rust#780]
# What

This issue is intended to be a list of all the issues we have in the wallet related to its database.

## Issues

These issues are related to RocksDB's [Rust crate](https://crates.io/crates/rocksdb) since most of these features are supported by RocksdDB itself but not by the crate:

- Lack of transactions. This is problematic if different threads modify the same database fields.
- Atomic updates. This one is kind of [supported by Rust crate](https://docs.rs/rocksdb/0.12.3/rocksdb/merge_operator/type.MergeFn.html) but it's not well document and the error handling is very primitive compared to how RocksDB implements it. On top of that, our database keys are encrypted for privacy, so there's no way to distinguish which keys are merged.
- Encryption support. Currently we have to encrypt/decrypt data manually, having something like [sqlcipher](https://github.com/sqlcipher/sqlcipher) would simplify our code greatly

## Current solutions

We are using locks to coordinate atomic updates and we perform encryption manually.

**Comment by mariocao** [comment]
Closed due to inactivity
