### ISSUE TITLE
Unify DataRequestReport and DataRequestInfo

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#792]
We have 2 very similar structures, `DataRequestInfo` and `DataRequestReport`. It could be better to only have one of them

**Comment by aesedepece** [comment]
Can you illustrate how similar are they?

**Comment by drcpu-github** [comment]
Volunteered for this refactor via Trello.

I took a look at the code and I think it makes most sense to completely remove DataRequestReport and replace it everywhere with DataRequestInfo as the latter is basically a superset of fields (with some extra indexing etc). Any other remarks and / or things I should look out for?

**Comment by drcpu-github** [comment]
@lrubiorod Any insights on above comment?
