### ISSUE TITLE
Propose a node logging improvement

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#807]
Propose how to improve the current node logging as right now there are several logs that could be improved.

**Comment by aesedepece** [comment]
#809 is relevant to this. There may be some other related issues out there. Shall we create a Node UX Epic?

**Comment by burguesia** [comment]
Current node logging is quite confusing. It would be more useful to have clear indications on:

1) Wether the node is synced or not. If it is not, an estimate an how long would it take to sync would be useful
2) data requests resolved
3) mined blocks
4) WIT mined

Also in the "how to run a Witnet node" post there should be a few notes on how to a) re-start a persistent container and b) run the most common commands (e.g. `getBalance`)

**Comment by aesedepece** [comment]
The available CLI commands are listed in the documentation, but they are
just not properly linked from the how to quickstart a node recipe:

https://docs.witnet.io/node-operators/cli/#commands

**Comment by ocuil** [comment]
Thanks so much !!! :-)

**Comment by mariocao** [comment]
Closed because several logging improvements have already been done.
