### ISSUE TITLE
Panic when synchronizing against a testnet with different radon operators

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#808]
Given a recent change of Radon operator codes, blocks from testnet-4 should be marked as invalid by the current master branch. The exact cause is this unwrap from the witnet_rad crate:

https://github.com/witnet/witnet-rust/blob/f5be51681d6f30849ddce22fdf8b02e86e48a7d4/rad/src/operators/array.rs#L46

But there are many more similar unwraps in that crate. Ideally we should replace all the unwraps with returning a result, and add tests so this does not happen again.

**Comment by aesedepece** [comment]
Agreed, all those unwraps should be replaced with `?` operator short-circuiting, or `.try_fold()` or `.map().collect()` if one wants to go functional.

**Comment by tmpolaczyk** [comment]
The unwraps were removed, but the tests are still missing. We need to test all the branches of `unpack_radon_script`, `unpack_radon_call`, `unpack_compound_call` and `unpack_subscript`.

**Comment by aesedepece** [comment]
Are we OK to close this?

**Comment by tmpolaczyk** [comment]
Only if there are tests
