### ISSUE TITLE
Synchronization logs should give better feedback about progress

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#809]
As a new node operator, I want the node logs to show an indication of progress (epoch number of the latest consolidated block, vs. epoch number of the target chain tip)

Something like this would be ideal:
```
[ INFO  witnet_node::actors::chain_manager::handlers ] Synchronization progress: 50.00% (11111 out of 22222). Latest synced block is 1w 2h 34m old.
```

**Comment by mariocao** [comment]
Closed in #933
