### ISSUE TITLE
Gracefully stop node

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#827]
In some places we have this piece of code:

    // Stop the node
    ctx.stop();

`ctx.stop()` will not stop the node, it will only stop the current actor. To stop the current system we could use `System::current().stop()` but that causes a panic in rocksdb...

**Comment by aesedepece** [comment]
How bad is this as of today?

**Comment by tmpolaczyk** [comment]
We haven't run into any problems, but I wouldn't consider it fixed.
