### ISSUE TITLE
Decide wallet component's fate

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#871]

**Comment by mariocao** [comment]
The discussion outputs were:
- List of high-level requirements for the wallet component (e.g. no encryption, querying capabilities, embedded, pub/sub, crate status, ACID properties, ...)
- Update to the team on currently being used `rocksdb` functionalities within wallet
- Tentative list of potential technologies to be assessed (rocksdb, sqlite, leveldb, lmdb)

As result, issue #889 is created to be done in the next sprints.

**Comment by aesedepece** [comment]
Is this a pass for now?

**Comment by mariocao** [comment]
Same as #889.
