### ISSUE TITLE
Modify logs to use NTP timestamps

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#882]

**Comment by tmpolaczyk** [comment]
Here's an example of env_logger using a custom formatter. I think it should be possible to modify the timestamp there:

https://github.com/sebasmagri/env_logger/blob/bfac6411adb05b7587b5de4acea0d5c3044ef029/examples/custom_format.rs

**Comment by aesedepece** [comment]
What are the trade-offs, performance-wise?

**Comment by tmpolaczyk** [comment]
It's just one `RwLock` read and one `Duration` addition per log. Should be negligible compared to the overhead of writing to stdout, but we should measure it anyway.

**Comment by aesedepece** [comment]
Do we still want this?

**Comment by tmpolaczyk** [comment]
I don't know, we have other issues with NTP currently :see_no_evil:
