### ISSUE TITLE
Assessment about last_epoch field in Version message

### ISSUE THREAD

**Issue by lrubiorod** [witnet/witnet-rust#888]
Currently last_epoch field in Version message is useless.
It is needed to do an assessment about its possibilities and implementing them or remove it

**Comment by aesedepece** [comment]
Does this still hold true?

**Comment by tmpolaczyk** [comment]
It looks like this is still unfixed, and most fields of the `Version` message are also unused. The only used fields are `sender_address` and `timestamp`, here: https://github.com/witnet/witnet-rust/blob/631dc672e62eee8866fa62306f5b8054ed5a6e55/node/src/actors/session/handlers.rs#L114

**Comment by aesedepece** [comment]
Moving this into "ready to estimate."

**Comment by aesedepece** [comment]
This should be acted upon before mainnet, @witnet/devs
