### ISSUE TITLE
Assess invalid reveals

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#894]
Define what should happen with invalid reveals:

* Empty array
* Not CBOR
* Invalid CBOR
* Wrong RADON type

And add tests

**Comment by aesedepece** [comment]
Right now they are all treated the same:
https://github.com/witnet/witnet-rust/blob/d09bc76159ba0d59361cb4bdce6dfa58470f29c4/node/src/actors/chain_manager/mining.rs#L377-L392

Basically, a malformed reveal equals a non-reveal. My reasoning for this was all about considering that the witness did not "keep its word" and failed to publish a reveal that is valid for its former commitment in time.

**Comment by aesedepece** [comment]
Is this still an issue? I think it isn't, right?

**Comment by tmpolaczyk** [comment]
Only if there are tests
