### ISSUE TITLE
Handle data requests with zero reveals

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#897]
Right now a data request with n commits but zero reveals cannot finish, and stays forever in reveal stage. That's because the result would be an error, and RADON error are still being implemented.

* Add RADON error `NoReveals`
* Implement logic in mining to handle this case. This should be similar to the existing `extra_reveal_rounds` logic, in fact there is a special check for data requests with zero reveals:

https://github.com/witnet/witnet-rust/blob/ba047719817a2d596b6958f03daa146ad20e3dd5/data_structures/src/chain.rs#L1562

* Add validations
* Add tests

**Comment by lrubiorod** [comment]
It will be solved in #945
