### ISSUE TITLE
dataRequestReport CLI method

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#898]
Currently there is a really nice `dataRequestReport` JSON-RPC method, which given a data request hash returns a lot of useful information. It would be nice to have a CLI method to get that information in a human readable format.

For example, there is a list of reveals but those reveals are returned as an array of bytes. The CLI method should parse that and print the RadonType. Same for the tally.

It would also be useful to print the data request transaction, which is not returned by the `dataRequestReport` JSON-RPC method, but we would need to implement the `getTransaction` JSON-RPC method (#498).

**Comment by aesedepece** [comment]
Let's make sure someone puts this on some whiteboard so it doesn't get oversighted when planning next sprints.

**Comment by aesedepece** [comment]
@witnet/devs I'd give this some priority as community members are craving for it.
