### ISSUE TITLE
Implement handshake protocol in Session actor

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#93]
#### Context
- The handshake protocol comprises a series of messages that need to be exchanged between peers before they can consider the session to be "consolidated", that is, suitable for using the rest of messages in the Witnet network protocol.
- [Documentation can be found here](docs).
- Handshaking ensures that peers use compatible network protocol versions.
- Handshaking uses timeouts to prevent DoS by lazy or adversarial peers.
- Handshaking is a reactive process that needs to be initialized by the peer who opened the connection (the one considering the session as "outbound") by sending a `version` protocol message. Once the initializer has been sent a satisfying `verack` response, the counterpart (the peer considering the session as inbound) will make the handshake in the opposite direction with `version`. Only after both have issued and received `version` and `verack` will the initializer consolidate the session.
- If the handshake takes more than a certain amount of seconds, the action should be killed using a "poison pill", thus dropping the connection.
- In the event of a failed handshake, the peer address should be removed from the list in `PeersManager`. In the future, we may want to blacklist it too.
- Consolidation is made possible by #94.

#### Actionables
- [x] Add variable for handshake timeout in configuration file.
- [x] Make `ConfigManager` read the handshake timeout variable.
- [x] Move session creation from `ConnectionsManager` to `SessionsManager`.
- [x] Make ~~`Session`~~ `SessionsManager` read handshake timeout from `ConfigManager` upon start.
- [x] Make `SessionsManager` pass the read handshake timeout to each session upon creation.
- [x] Make `Session` initialize a the handshake timeout upon start.
- [x] Make `Session` issue a `version` protocol message if this is an outbound session.
- [x] Make `Session` handle `verack` messages.
    - If inbound and we already sent a `verack` to the other side, consolidate.
    - Ignore otherwise.
- [x] Make `Session` handle `version` messages.
    - If compatible, answer `verack`.
        - If this is an inbound session, send `version` immediately thereafter.
        - If outbound and we already got a `verack` from the other side, consolidate.
        - Ignore, remove from `PeersManager` and fail with poison pill.
    - If incompatible, ignore, remove from `PeersManager` and fail with poison pill.
- [x] Make `Session` cancel timeout upon consolidation.

[docs]: https://docs.witnet.io/protocol/network/#handshake-version-verack

**Comment by mariocao** [comment]
Right now, as discussed, we are not checking any version field for the handshake as they will change in the upcoming Sprint, i.e. there are not incompatible peers for now. :smile:

**Comment by mariocao** [comment]
Cancellation of timeout is done by checking if the session is consolidated after the pre-configured period of time (cancellation is not possible with actix).
