### ISSUE TITLE
`TryFrom<&cbor::value::Value> for RadonTypes` is using CBOR tag `37` for errors instead of `39`

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#936]
The current convention for serializing Witnet errors is to use `39` as the CBOR tag. However, the current deserializer (`TryFrom<&cbor::value::Value> for RadonTypes`) is using `37`.

The good one is `39`.

**Comment by peteroupc** [comment]
Note that tag 37 is specified as Binary UUID, and tag 39 is specified as an identifier.  See the IANA registry at: https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml .

**Comment by aesedepece** [comment]
@peteroupc Thanks for your comment! We are using tag `39` instead of something specific just for the sake of brevity.
