### ISSUE TITLE
Provide type-explicit reducers

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#989]
## Issue description

As per recent changes in the data structures of the protocol, the aggregation and tally stages no longer rely on RADON scripts but rather appoint one pre-defined reducer and many pre-defined filters.

As a consequence, we lost the ability to force the output type of a stage to the one of our convenience. For example, a request whose source type is `Integer` currently results in a tally of type `Float` if a `AverageMean` reducer is used anywhere in the pipeline.

### Approach A
One easy fix would be for reducers to honor the input type, i.e. `AverageMean` would return `Float` when applied on `Array<Float>` and `Integer` when the input is `Array<Integer>`.

Note however that having `Integer` sources but wanting a `Float` tally is perfectly legit, and is indeed a behavior that we can foresee many users to expect.

Under that scenario, if an user wants a `Float` average from `Integer` sources, the source scripts themselves should cast the integer to `Float`, so `AverageMean` deals with them accordingly instead of rounding them up or down at the end.

The main merit for this approach is that no consensus-critical data structures need to be changed, and it only affects the business logic in the node, but nothing else in any other component.

### Approach B
A different approach is splitting some reducers into multiple identifiers so we are explicit about the expected output type, e.g. `AverageMeanInteger` vs. `AverageMeanFloat`. 

The main merit for this approach is explicitness.

## Proposal

I'm not settled on recommending one approach or the other yet. Let's gather feedback and discuss.

**Comment by aesedepece** [comment]
I personally suggest this should be prioritized for the next release, as until solved, using Witnet from Ethereum has some serious usability issues.

**Comment by aesedepece** [comment]
@lrubiorod any comments?

**Comment by lrubiorod** [comment]
I like the first one, to avoid create redundant reducers. But we should ensure that there will be enough documentation to people dont misunderstand the correct functionality

**Comment by tmpolaczyk** [comment]
So will this apply to all reducers or only `AverageMean`?

**Comment by aesedepece** [comment]
I guess it's a general contract for all reducers: `Fn(Array<T>) -> T`
